### PR TITLE
etherington-lieske

### PR DESCRIPTION
**Pull request by tretherington**
**AUTHOR**

Dear @ReScience/editors,

I request a review for the following replication:

### Original article

**Title: Resampling methods for evaluating classification accuracy of wildlife habitat models**  
**Author(s): Verbyla DL, Litvaitis JA**  
**Journal (or Conference): Environmental Management**  
**Year: 1989**  
**DOI: https://doi.org/10.1007/BF01868317**  
**PDF: https://www.researchgate.net/profile/John_Litvaitis/publication/226300610_Resampling_methods_for_evaluating_class_accuracy_of_wildlife_habitat_models/links/53d4fd790cf2a7fbb2ea2b1d/Resampling-methods-for-evaluating-class-accuracy-of-wildlife-habitat-models.pdf?origin=publication_detail**   

### Replication

**Author(s)**:   @tretherington and David Lieske
**Repository**:  https://github.com/tretherington/ReScience-submission/tree/etherington-lieske
**PDF**:  https://github.com/tretherington/ReScience-submission/blob/etherington-lieske/article/etherington-lieske-2018.pdf (Apologies, but really struggling to get pandoc cross-ref working, but hopefully this pdf will suffice to start the process)
**Keywords**:  ecology, wildlife, habitat, model
**Language**:  Python
**Domain**:  Ecology

### Results

* [X] Article has been fully replicated
* [ ] Article has been partially replicated
* [ ] Article has not been replicated

### Potential reviewers
Based on an 'ecology' and 'Python' combination, @tpoisot and @jsta may be good potential reviewers.

---

**EDITOR**

* [x] Editor acknowledgment - @tpoisot
* [x] Reviewer 1 - @jkitzes accepted `2018-10-31` :jack_o_lantern:
* [x] Reviewer 2 - @laurajanegraham accepted `2019-01-30`
* [x] Review 1 decision [accept/reject]
* [x] Review 2 decision [accept/reject]
* [x] Editor decision [accept/reject]

### CODE REVIEW

**Comment by rougier** [comment]
@tretherington Thank you for you submission. An editor will be assigned soon.

**Comment by rougier** [comment]
@tpoisot Can you edit this submission

**Comment by rougier** [comment]
@tpoisot 👏

**Comment by rougier** [comment]
@tretherington I'm not forgeting you ! I think @tpoisot won't be available before 10/10. I'm looking for another editor. 

@karthik Could you handle this submission ?

**Comment by karthik** [comment]
Hi @rougier I am on continuous travel through middle of October so I would recommend another editor for this submission.

**Comment by rougier** [comment]
@karthik Ok, thanks.
@dmcglinn could you edit this submission?

**Comment by dmcglinn** [comment]
Hey @rougier, sorry but I cannot help with this submission as an editor. I'm over committed this month.

**Comment by rougier** [comment]
@tretherington  As you can see above, we've some problems finding the proper editor but I think @tpoisot will be available in ten days. If it's ok with you we can wait for some more days or I can send a call for edit to all reviewers. What do you think ? Or maybe @khinsen knows someone ?

**Comment by khinsen** [comment]
@rougier No, sorry, I don't know anyone in ecology other than the people who are already on our editor/reviewer list!

**Comment by dmcglinn** [comment]
Here are some other potential ecology folks that may be able to help with this @ethanwhite @ahhurlbert @jarioksa @gavinsimpson @dschwilk just to name a few that I know would all be great as reviewers or editors.

**Comment by tretherington** [comment]
Hi @rougier no worries about the delay, all quite understandable.  Happy to wait for a bit longer if you think a good option is on the horizon. :)

**Comment by rougier** [comment]
@tpoisot Do you have more time now to edit this submission?

**Comment by rougier** [comment]
@tpoisot 🛎

**Comment by rougier** [comment]
@tpoisot @karthik Could you edit this submission (we are very late now)

**Comment by tpoisot** [comment]
On it. I'll invite reviewers as soon as I reach my office.

**Comment by tpoisot** [comment]
**Reviewer invitations**

@gvdr 
@jkitzes
@emchristensen

Would one of you be available to review this article? I can walk you through the review process if needed.

**Comment by gavinsimpson** [comment]
Sorry @dmcglinn I'm just catching up with various requests through Github - I can't review this just now as I'm over committed at the moment (& python is not really my wheel house).

**Comment by jkitzes** [comment]
@tpoisot I believe I can get to this - when do you need it by?

**Comment by tpoisot** [comment]
@jkitzes 3 weeks?

**Comment by jkitzes** [comment]
@tpoisot Sure, I can do that. Anything to know about the review process other than what's in the reviewer guidelines?

**Comment by tpoisot** [comment]
Ping @gvdr and @emchristensen

**Comment by emchristensen** [comment]
@tpoisot I'm sorry but I"m not going to be able to take this on at the moment (and I really don't know much about python)

**Comment by jkitzes** [comment]
**GENERAL COMMENTS**

In this manuscript, the authors create a up-to-date Python implementation of an analysis of several different resampling methods, originally published by Verbyla and Litvaitis. They verify the authors' original conclusion, which is that resubstitution produces biased estimates of classifier error, while several other procedures (including cross-validation, jacknifing, and bootstrapping) produce unbiased estimates. This test is done in the context of a species distribution model, but it applies more generally as well.

I found the manuscript clear and the results reasonable. I would consider the original study to be successfully replicated, while noting that this new implementation actually goes beyond the original analysis and extends its findings in some respects. The code in this PR actually does not run on my system, but with the two modifications below, it runs successfully and reproduces the key figure. 

**CODE COMMENTS**

While I did not go through the code line-by-line to verify its accuracy, the code is written clearly and understandably overall. The implementation appears to follow what the authors describe in the manuscript. I did encounter two issues that needed to be fixed, however, at least on my system:

First, there appears to be one major bug. In the function `peLDA`, it appears that the function forgets to actually create an `LDA` object that has the methods `fit` and `predict` available. Changing this function to

```
# Define a function to calculate prediction errors from LDA model
def peLDA(trainPA, trainEV, testPA, testEV):
    # Create and fit model
    LDA_obj = LDA()
    LDA_obj.fit(trainEV, trainPA)
    # Predict against test data
    predicts = LDA_obj.predict(testEV)
    # Calculate and return the prediction errors
    return(np.abs(testPA - predicts))
```

will correct the problem.

Second, I did not have LaTeX installed locally on the machine where I tested this code, and the matplotlib figure will not save (throws an error) due to the line `plt.rc('text', usetex=True)`. Changing this to `False` allows the figure to save - the text is not rendered as nicely, of course, but everything is still in the right place. I would suggest either setting this to `False` by default or noting that LaTeX is a dependency.

**ARTICLE COMMENTS**

A few fairly minor comments on the text:

1.  The authors appear to consistently mis-spell the second author's name in the paper they are replicating - it should be "Litvaitis" not "Litvatis".
1.  There's a vertical bar missing from Eq. 3.
1.  I think it would help to link the terminology here back explicitly to that used by Verbyla and Litvaitis. It's fairly obvious for someone used to looking at this, but it couldn't hurt to say things like "Verbyla and Litvaitis use 'Cross-validation' to refer to Hold-out cross-validation performed for one repitition", and so on for the other methods.
1.  While it's logical and useful to test three types of hold-out validation here, I would note that there does not appear to me to be any ambiguity about which case Verbyla and Litvaitis were envisioning - they state under "Cross-validation" that "only one estimate of accuracy is made", which to me indicates that they used H=1. This would also somewhat explain their general statement about the imprecision of the estimate of classification accuracy.
1.  I would suggest reordering the description of approaches in either the "Resampling methods" or "Computational experiment replication" section so that they occur in the same order in both.
1.  I would suggest stating, just for clarity, that the replication here used a LDA for prediction as well.

**Comment by tretherington** [comment]
Hi @jkitzes thanks for that - very helpful stuff!

**Comment by tretherington** [comment]
Hi @jkitzes apologies for the slow response.  I've just [committed](https://github.com/ReScience/ReScience-submission/pull/52/commits/7f55f9c78975a6b442e759af12e201e7cd6c7422) some modified Python code based on your suggestions.

I'm very embarrassed  about the LDA model bug you spotted, as the code didn't run on my system either :( but I have fixed based on the code you suggested, so everything now works again :)

Thanks also for spotting the LaTeX dependency issue which would have never crossed my mind.  I'm keen to keep the LaTeX font in the figure to maintain consistency between the figure annotations and the equations in the manuscript.  But I have now included a check for a LaTeX installation within the code, so the code should run and save a figure using 'normal' font if LaTeX isn't installed.  I've also made notes about the LaTeX dependency for exact replication of the figure in the README.md files for those people who really want to do that.

**Comment by tretherington** [comment]
And again @jkitzes I've made a seperate [commit](https://github.com/ReScience/ReScience-submission/pull/52/commits/cb31c3862eb22e1544ccf10980fdf97651a6b4d2) that modifies the manuscript with reference to your article comments above:

1. Corrected - thanks for spotting.
2. Corrected - again, thanks for a good spot.
3. This is a good idea, and we have now made sure that where there is any change in terminology we specifically link our descriptions of each resampling method back to the terminology used by Verbyla and Litvaitis.
4. OK, fair point I think rereading that again myself.  I still think there is ambiguity there, but I have reworded that section to recognise that Verbyla and Litvaitis were likely talking about H=1.
5. I understand where you are coming from here, as it would seem logical to have them in the same order, especially if the parameters for each method were chosen independently.  However, we have put the hold-out methods last as some of the choices made here relate to earlier decisions in describing other methods.  We chose H=200 to match the bootstrap B=200 which is described/explained in the previous section.  So we think the current order is the most logical as the methods are described in their order of interdependence.
6. Good point, and we should be clear about that, so I have added that information to the section 4.1.

Thanks again for the suggestions and picking up those embarrassing errors.

**Comment by tretherington** [comment]
Mostly as a note to self, I still can't get pandoc-crossref to install properly to the point where I can produce a properly typeset pdf, so the pdf is generated using 

`pandoc -s -o etherington-lieske-2018.pdf etherington-lieske-2018.md`

which at least typesets the texts, equations, and figure which will hopefully continue to suffice for any further revisions.

**Comment by jkitzes** [comment]
@tretherington All looks good to me. No worries about that bug, I figured you were running it interactively or something and had the correct object hanging around your the environment somehow. Looks good to me now.

@tpoisot I recommend this for acceptance.

**Comment by tretherington** [comment]
Hi @tpoisot I appreciate things will have slowed down over Christmas and New Years, but I was just wondering where we are at - are you still looking for a 2nd reviewer?

**Comment by rougier** [comment]
@tretherington Sorry for the delay and I think second reviewer has not been assigned yet.
Let see if we can find one: @ReScience/reviewers A reviewer in ecology is needed for reviewing "[Re] Resampling methods for evaluating classification accuracy of wildlife habitat models!"

**Comment by rougier** [comment]
@tpoisot Gentle reminder

**Comment by tpoisot** [comment]
@rougier @tretherington I am still trying to find a second reviewer - if the author could suggest someone, that would help (and note that I'm on parental leave until March, so not as reactive as I'd like).

**Comment by tretherington** [comment]
Hi @tpoisot no worries, I was most just querying next steps as this is my first interaction with ReScience.  When you get a chance I wonder if @jsta would be well placed as he is listed on the reviewers list as doing both ecology and Python.  Or you could ask @laurajanegraham who does ecological modelling and knows Python.

**Comment by laurajanegraham** [comment]
I'd be happy to review, but I have a busy couple of weeks so it wouldn't be until w/c 11th Feb at the earliest. 

Excited to hear about ReScience - a great initiative!

**Comment by tpoisot** [comment]
@laurajanegraham excellent! I will list you as second reviewer.

**Comment by tpoisot** [comment]
@laurajanegraham -- gentle reminder about the review

**Comment by laurajanegraham** [comment]
Thank you for the reminder. Apologies for the delay. I've made myself a note to do this next week (at a conference this week).

**Comment by laurajanegraham** [comment]
## GENERAL COMMENTS

This manuscript outlines a Python implementation of the simulation study from Verbyla and Litvaitis 1989. In this, they compared a number of resampling approaches for the validation of species-environment models. 

I am satisfied that the study has been replicated (impressive given the lack of detail to go on!); the manuscript is written clearly; and the code will prove useful for those doing such validation in Python. 

## CODE COMMENTS

I went through the code in detail and can confirm that the logic is sound. 

I had one small issue in that I needed to update my numpy version in order to get it to work. It may be worth adding a dependency note that numpy > 1.13 is required (this is when the `isin` function was implemented). 

## MANUSCRIPT COMMENTS

It seems the previous review caught most of the issues. I have two comments: 

1. In the first sentence of **Bootstrap cross-validation**, it should be method rather than methods. 

2. The references and figure labels are not rendering correctly (this is perhaps due to the issues with the template outlined above?). 

I recommend this for acceptance.

**Comment by tretherington** [comment]
Hi @laurajanegraham thanks so much for taking the time to take a look at our replication!

Regarding your code comments, the versions required/used are noted in the READMEs for both the  [repository](https://github.com/tretherington/ReScience-submission/tree/etherington-lieske) and the [code](https://github.com/tretherington/ReScience-submission/tree/etherington-lieske/code).  So I'm not sure I can do much else, and given NumPy 1.13 is almost a couple of years old, I would expect most people to have a required NumPy version installed.  Happy to take a suggestion if you can think of anything else I can sensibly do.

Regarding the manuscript comments, thanks for spotting the typo, I've corrected that.  The rendering of the references and figure labels continues to elude me as I still can't get pandoc-crossref to install happily.  But I'm hoping that I've formatted the files correctly such that the pdf should generate correctly once the editorial updates are done.

**Comment by tretherington** [comment]
Hi @tpoisot I just wanted to apologise in advance for failing to produce the typeset pdf as I continue to struggle to get pandoc-crossref working for me.  I'm hoping you may be able to generate the pdf for me, and while I've tried to carefully follow the required format, please do let me know if there are changes required and I'll get on them ASAP.

**Comment by rougier** [comment]
@tretherington Do you need some help for building the PDF (you can mail me directly or open a specific issue such as not to "pollute" the review)

**Comment by dimpase** [comment]
Just for fun, I tried running the code, and it's all working fine, with a non-anaconda Python 3.6 on Gentoo Linux, and whatever the versions of dependencies are now current in Gentoo (which is a rolling release; numpy is version 1.16.1).

One minor remark - I did not have `dvipng` installed, and so after 1000 runs it all errored out. Perhaps mentioning `dvipng` (called from Matplotlib, I gather) in prereq's would be helpful.

**Comment by tretherington** [comment]
@tpoisot article correctly typeset now when you have some time to review

**Comment by tretherington** [comment]
Hi @dimpase thanks for providing another test of the code :smiley:!  I've added a comments about needing a ```dvipng``` installation in the README.

**Comment by laurajanegraham** [comment]
@tretherington Ah yes, I see that in the README now. That's absolutely fine then; nothing else that I would suggest. Also, not sure why I had such an out of date version of numpy!

@tpoisot I recommend this for acceptance

**Comment by tpoisot** [comment]
@rougier following the two positive reviews, I'm happy to recommend acceptance of this article. I'm rusty on the next steps (and @tretherington will need to resolve the issues with the Makefile first anyways).

**Comment by rougier** [comment]
See http://rescience.github.io/edit/ but I copied it below (I can't believe the procedure is that complex. but this will much much simpler soon).

- [ ] Lock the conversation on the original PR
- [ ] Ask the author(s) for keywords if they haven’t provided them already.
- [ ] Import the authors’ repository into the ReScience archives (https://github.com/ReScience-Archives) using the naming convention “Author(s)-YEAR”
- [ ] Add a new remote (named rescience) in your local copy of the repository that points to the newly imported repository (the one on ReScience-Archives)
- [ ] Update article metadata:

    - Editor name
    - Reviewer 1 name
    - Reviewer 2 name
    - Submission date
    - Publication date
    - Article repository
    - Code repository
    - Notebook repository (if necessary)
    - Data repository (if necessary)
    - Volume, issue and year
    - Article number (after reserving the number in the dedicated [GitHub issue](https://github.com/ReScience/ReScience/issues/48))

- [ ] If the article name is not Author(s)-YEAR.md, rename it
- [ ] Rebuild the PDF and check everything is OK
- [ ] Merge the rescience branch into master
- [ ] Push these changes onto the rescience remote repository
- [ ] Make a new release:

    Release version number is 1.0
    Release name is Author(s)-YEAR-1.0

- [ ] Download the zip file and rename it to Author(s)-YEAR-1.0.zip
- [ ] Upload this zip file to [Zenodo](https://zenodo.org/deposit/?c=rescience).
       You will have to fill several fields:

    - Name of the journal is ReScience
    - Under “Communities” add “ReScience journal”
    - Under “Contributors” add yourself with role “Editor”.
    - Don’t forget keywords

- [ ] Announce publication in the PR (and quote the DOI, see
    [#3](https://github.com/ReScience/ReScience-submission/pull/3) for example)
- [ ] Make a PR to the [Web site repository](https://github.com/ReScience/rescience.github.io) in order to update the page [rescience.github.io/read](http://rescience.github.io/read/).  This requires creating a new post (directory `_posts`) based on this  [model](https://raw.githubusercontent.com/rougier/rescience.github.io/master/_posts/2015-08-14-Topalidou-Rougier.md) because the page is composed from the posts of type `article`.
- [ ] Make a PR to update [Rescience/Volume X - Issue Y.md](https://github.com/ReScience/ReScience)
 - [ ] Close the PR without merging

**Comment by tretherington** [comment]
@tpoisot thanks for finding time for this.  All should be good with the Makefile and pdf now, but do let me know if you need anything else from me.

**Comment by tretherington** [comment]
Hi @tpoisot just checking if you are waiting on me for something - I think I've done everything, but please let me know if I've missed something

**Comment by tpoisot** [comment]
@tretherington there are still conflicts with the Makefile -- when this is solved, @ReScience/editors will be able to assign an article number.

**Comment by tretherington** [comment]
@tpoisot Aha, yes, same issue corrected in both mine and master Makefile, sorry should have spotted and realised that was an issue.  All good now I think.

**Comment by tretherington** [comment]
Hi @tpoisot, any chance this could be progressed?  I appreciate you will be busy, but I have an end of project deadline coming up, and it would be great to have a published version of this for reporting purposes.  I will help in whatever way I can!

**Comment by tpoisot** [comment]
I missed the message with infos from @rougier -- I will go through the upload and publication on friday

**Comment by rougier** [comment]
@tretherington @tpoisot I just put the new website online such that the publication process should be easier. I can help on that. What I need at this point is the PDF of the article and a metadata file following this model: https://github.com/ReScience/template/blob/master/metadata.yaml.

@tretherington If you can fill in the metadata and give it back to me, I can probably publish it today. If you want to use the new article template design, it might necessitate a bit more work (from you) but we can also do it.

**Comment by tretherington** [comment]
@rougier I like the look of the new publication process.  I think basing things on LaTeX will smooth the process out significantly - I know I spent a lot of time trying to get pandoc working properly, and my paper was first written in LaTeX so I'm back to where I started!

I wasn't sure how best to create/submit the new PDF without (a) breaking the link to the review here, or (b) duplicating the paper by submitting again.  So I'm hoping you might be able to figure out the best way to blend my submission under the old system into a paper in the new system.  To help you do that I've created a [new folder](https://github.com/tretherington/ReScience-submission/tree/etherington-lieske/article-latex) in my pull request that contains the metadata.yaml and content.tex needed to generate the PDF which I have also done (new paper layout/style looks good!).

I think the only things outstanding are some urls and dois for the metadata, but as I've said already, I was hoping you might be able to fill those in as you will understand better how to mesh the two systems.

Hope that is all OK, and please just let me know if you need anything else.

**Comment by rougier** [comment]
Perfect ! I will get the DOI from Zenodo and rebuild your PDF. Last thing is I need a code DOI (in case your repo disspaear sometime in the future). Can you deposit it on Zenodo and give me back the DOI?

**Comment by tretherington** [comment]
@rougier many thanks!

I have deposited the repository on [Zenodo](https://zenodo.org/record/3229408) with DOI: 10.5281/zenodo.3229408

**Comment by rougier** [comment]
Can you fill editor and reviewer name/orcid ? volume is 5, issue is 1 (and also, can you fill the code URL and DOI).

+ submission date + publication date (28/05/2019)

**Comment by tretherington** [comment]
Hi @rougier I think that is all the metadata expect the article number, doi, and url

**Comment by rougier** [comment]
Can you  check if https://sandbox.zenodo.org/record/294119 seems correct ?
(This is not the real DOI because this is Zenodo sandbox)

**Comment by tretherington** [comment]
@rougier the article pdf looks correct to me!

**Comment by rougier** [comment]
Done! https://rescience.github.io/read/#volume-5-2019

**Comment by tretherington** [comment]
Thanks for all your help @rougier ! Having now had some of my work replicated and having replicated someone else's work in ReScience, I've become a big fan of the journal.

**Pull request closed without merging**
