### PR TITLE
Review request: Petchey, Plebani, Pennekamp

### PR DESCRIPTION
**Pull request by opetchey**
Dear @ReScience/editors,

  I request a review for the reproduction of the following paper:
- Benincà, E., Huisman, J., Heerkloss, R., Jöhnk, K.D., Branco, P., Van Nes, E.H., Scheffer, M. & Ellner, S.P. (2008) _Chaos in a long-term experiment with a plankton community._ Nature, 451, 822–825.
  
  I believed the original results have been adequately reproduced as explained in the accompanying [article](https://github.com/opetchey/ReScience-submission/raw/petchey-plebani-pennekamp-2016/article/article.pdf).
  
  The repository lives at [https://github.com/opetchey/ReScience-submission/tree/petchey-plebani-pennekamp-2016](https://github.com/opetchey/ReScience-submission/tree/petchey-plebani-pennekamp-2016)

Best wishes
Owen Petchey

---

**EDITOR**
- [x] Editor acknowledgment (@tpoisot) `Feb 23, 2016`
- [x] Reviewer 1 (@yoavram) `March 3, 2016`
- [x] Reviewer 2 (@FedericoV) `March 3, 2016`
- [x] Review 1 decision [accept] `April 5, 2016`
- [x] Review 2 decision [accept] `April 13, 2016`
- [x] Editor decision [accept] `April 13, 2016`

### CODE REVIEW

**Comment by opetchey** [comment]
The research area of the original publication is ecology, so Timothée Poisot or Karthik Ram may be appropriate editors.

**Comment by rougier** [comment]
**EDITOR-IN-CHIEF**

Thank you very much for the submission (as well as the suggested name of the reviewers !). An editor should soon acknowledge the submission to start the review. Don't hesitate to remind us if it was not the case in the next few days.

@tpoisot Can you handle the submission ?

**Comment by tpoisot** [comment]
**EDITOR**

Gladly.

**Comment by opetchey** [comment]
**AUTHOR**

Thanks Timothée. Looking forward to the process.

**Comment by tpoisot** [comment]
**EDITOR**

Hi @opetchey -- thanks for the submission. While I am contacting potential reviewers, could you add a `LICENSE` file at the root of the repository (or in the `code` folder)? You can go [here](http://choosealicense.com/) for a list of OSI compliant licenses.

**Comment by tpoisot** [comment]
**EDITOR**

@FedericoV and @yoavram - can you take up the mantle of being **REVIEWER 1** and **REVIEWER 2**?

**Comment by FedericoV** [comment]
**REVIEWER 2**

ACCEPT.

Let me read this in more detail to make sure I am up to the task.  I'll try to answer by tomorrow.

Looking at it in more detail: The math part is fine, but you used R to do all the simulations/analysis, which I am not very familiar with at all.

I can try to handle it if we cannot find anyone else, but I'd rather have someone more experienced in R than me do the review.

**Comment by yoavram** [comment]
**REVIEWER 1**

I'll be happy to do it. I'm not familiar with most of the methods, but I think I know enough R and I'm interested in the scientific question, so maybe I'm a decent example of the target audience of this code.

This is my first review for ReScience, so @tpoisot please stop me if I'm making a mess.

I cloned the repo and got one comment already: I can't find an explanation of how to reproduce the results. The README in the code folder says that the Rmd file produces all elements of the article (figures?), but can the authors add instructions on how to use this file? Preferably in one of the README files?

**Comment by opetchey** [comment]
Thanks... I added the required packages to the readme file in the code folder. And added some convenient code to the report.rmd file to install them.

**Comment by tpoisot** [comment]
**EDITOR**
Thanks @opetchey -- @yoavram and @FedericoV , you can start reviewing now.

**Comment by yoavram** [comment]
OK, I opened `report.Rmd` in RStudio and clicked the "Knit" button.
On line 43 I got an error: "there is no package called 'devtools'.".
So you might want to check that it's installed before calling it, and install it if it's not installed. Or at least add it to the requirements?

**Comment by yoavram** [comment]
After installing everything and running again, I get:

```
Quitting from lines 543-553 (report.Rmd) 
Error in cor.coefs[oo, oo] : subscript out of bounds
Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval
In addition: Warning messages:
1: Removed 27 rows containing missing values (geom_point). 
2: Removed 27 rows containing missing values (geom_point). 
3: Removed 27 rows containing missing values (geom_point). 
4: Removed 27 rows containing missing values (geom_point). 
Execution **halted**
```

Everything up to that point worked great - I ran it line by line and no errors, nice figures.

``` R
> dim(cor.coefs)
[1] 10 10
> oo
 [1] 10  9  8 11 12  6  5  3  4  2
```

So the error seems to occur because `oo` has values 11 and 12 which are too big for `cor.coefs`.

Here's my 

session info:

```
Session info ------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.1.3 (2015-03-09)
 system   x86_64, mingw32             
 ui       RStudio (0.99.491)          
 language (EN)                        
 collate  Hebrew_Israel.1255          
 tz       Asia/Jerusalem              
 date     2016-03-23                  

Packages ----------------------------------------------------------------------------------------------
 package   * version date       source        
 devtools    1.10.0  2016-01-23 CRAN (R 3.1.3)
 digest      0.6.9   2016-01-08 CRAN (R 3.1.3)
 htmltools   0.3.5   2016-03-21 CRAN (R 3.1.3)
 memoise     1.0.0   2016-01-29 CRAN (R 3.1.3)
 Rcpp        0.12.3  2016-01-10 CRAN (R 3.1.3)
 rmarkdown   0.9.5   2016-02-22 CRAN (R 3.1.3)
 yaml        2.1.13  2014-06-12 CRAN (R 3.1.3)
```

I'm adding the workspace as a zipped RData file. Hopefully this information will be helpful.
I'll wait for your response before proceeding.

[petchey.zip](https://github.com/ReScience/ReScience-submission/files/185530/petchey.zip)

**Comment by opetchey** [comment]
@yoavram Thanks... probably I saw why this was happening and fixed it. Please can you try again?

**Comment by yoavram** [comment]
I updated the code, getting this error:

```
> cor.coefs1 <- cor.coefs[oo,oo]
Error in cor.coefs[oo, oo] : subscript out of bounds
In addition: Warning messages:
1: Removed 27 rows containing missing values (geom_point). 
2: Removed 27 rows containing missing values (geom_point). 
3: Removed 27 rows containing missing values (geom_point). 
4: Removed 27 rows containing missing values (geom_point). 
5: In rbind_all(out[[1]]) : Unequal factor levels: coercing to character
6: Grouping rowwise data frame strips rowwise nature 
7: In rbind_all(out[[1]]) : Unequal factor levels: coercing to character
8: In rbind_all(out[[1]]) : Unequal factor levels: coercing to character
```

**Comment by opetchey** [comment]
Sorry about that. Please could you again send me the workspace just after this error occurs (i.e., to and including line 536)?

**Comment by FedericoV** [comment]
Hi,

I'm a complete newbie to R, so I had to spend a fair bit of time setting up
the environment to reproduce the code.  For the record, on a fresh R-Studio
install, I had to issue the following commands

output:install.packages(c("tidyr","dplyr", "lubridate", "stringr",
"ggplot2", "RCurl", "pracma", "oce",
"tseriesChaos", "reshape2", "mgcv", "repmis",
"magrittr", "knitr"))
install.packages(c("devtools"))
install.packages(c("devtools"))
install.packages(c("RCurl"))
install.packages(c("repmis"))

The first time I tried installing devtools (through r-studio) it failed
because it had a dependency on libcurl that I had to install via apt-get:

sudo apt-get -y build-dep libcurl4-gnutls-dev
sudo apt-get -y install libcurl4-gnutls-dev

Again - the errors were relatively straight forward, and a more experienced
R user would have probably set all this up before hand, but for people that
are not familiar with how to set up an R environment, more details would
have been helpful.

After installing all the dependencies, I got the same error as Yoav in the
exact same spot (line 534).

**Comment by opetchey** [comment]
@FedericoV Thanks for the feedback on the install. Sorry that I didn't already provide this. I am putting this information in the document.

**Comment by opetchey** [comment]
@FedericoV @yoavram Please can you tell me what R says when you run in the Console this `type.convert`? (I think this may be set differently for you.)

I've in any case attempted a fix based on what I so far see. If you have a chance, please see if it works.

many thanks
Owen

**Comment by yoavram** [comment]
Good job, I was able to knit the HTML using commit a65129c.

**Comment by yoavram** [comment]
I've now gone over the reproduced HTML and the manuscript. 
The following is based on commit a65129c.

Major issue:
- Fig 3 is totally different in my reproduction (see attached html in zip file). What did I mess up?

Minor issues: 
- Fig 2,4 (but not 7) - _order_ of panels in my reproduction is different from the submitted PDF. 
- "the course here on github": I recommend just hyperlinking the words "on github" rather than "here" to [promote accessability](https://www.amherst.edu/help/make_accessible). Also in other places and in the ms ("about the course here" etc.)
- Maybe add somewhere "Tested on ..." - I use Win 7 64-bit with R 3.1.3.
- Typo: "with _comman_ as the decimal separator"
- Commented out sections: I suggest to either remove or add a comment on why this is commented out
- "should give true" -> "should give TRUE", and also see next bullet
- "## should be 12,12": consider using assertions - `stopifnot`, [assertr](https://github.com/tonyfischetti/assertr), [assertthat](https://github.com/hadley/assertthat).
- "chosen rather randomly!": maybe change to "arbitrary"?
- manuscript: "15–30days" missing space?

[report.zip](https://github.com/ReScience/ReScience-submission/files/191637/report.zip)

**Comment by opetchey** [comment]
Please ignore this comment, and see below.

Thanks @yoavram 
Following is a commit in which I've addressed all your minor issues; thank you very much for pointing them out. Only the figure 2 & 4 issue I am not sure if I fixed.
The major issue I attempted to fix. Please check this.
(Apologies I can't be sure of some of the fixes, but your computer / R is behaving differently from mine, and I can't figure how to make mine behave the same as yours. At least one difference is how dplyr::gather() converts the key variable to factor variable for me, but leaves it as a character variable for you.)

**Comment by tpoisot** [comment]
@opetchey / @yoavram does either of you have a `.Rprofile` (or equivalent) file, setting default options?

Mine has the line

``` R
options(stringsAsFactors=FALSE)
```

and it changes the way strings in `data.frame`s are handled.

**Comment by opetchey** [comment]
Thanks @yoavram 
Following is a commit in which I've addressed all your minor issues; thank you very much for pointing them out. Only the figure 2 & 4 issue I am not sure if I fixed.
The major issue I attempted to fix. Please check this.
(Apologies I can't be sure of some of the fixes, but your computer / R is behaving differently from mine, and I can't figure how to make mine behave the same as yours. At least one difference is how dplyr::gather() converts the key variable to factor variable for me, but leaves it as a character variable for you.)

@tpoisot I think the problem was in the gather() function of dplyr, the behaviour of which is not controlled by stringsAsFactors. But in the latest fix, I think I specified the behaviour of gather() explicitly, and that hopefully this fixes the difference in behaviour.

**Comment by yoavram** [comment]
I pulled and ran again, panels are still sorted alphabetically.

**Comment by tpoisot** [comment]
@yoavram -- reproducting the _manuscript_ is not as important as reproducing the _contents_ of the figures -- @rougier can you confirm? 

If you managed to reproduce the contents of the figures, this will be sufficient.

**Comment by rougier** [comment]
Yes, the main point of the review is first to check whether original results can be replicated (or not) using the proposed new implementation. But ensuring anyone can re-run the replication is equally important of course. Concerning possible layout issues in the new manuscript, we can try to fix them after the review if the paper is accepted.

**Comment by yoavram** [comment]
Sure, I agree. I only listed it as a minor issue because I got a layout that was different from the one the authors got.

**Comment by opetchey** [comment]
@yoavram please can you send me an image of your workspace after all the code is run?
And also what appears in the console if you run `type.convert`. E.g., I get:

```
> type.convert
function (x, na.strings = "NA", as.is = FALSE, dec = ".", numerals = c("allow.loss", 
    "warn.loss", "no.loss")) 
.External2(C_typeconvert, x, na.strings, as.is, dec, match.arg(numerals))
<bytecode: 0x7fa355108d40>
<environment: namespace:utils>
```

**Comment by yoavram** [comment]
Sure! I get what you get, I think:

``` R
> type.convert
function (x, na.strings = "NA", as.is = FALSE, dec = ".", numerals = c("allow.loss", 
    "warn.loss", "no.loss")) 
.External2(C_typeconvert, x, na.strings, as.is, dec, match.arg(numerals))
<bytecode: 0x000000001be04680>
<environment: namespace:utils>
```

See attached zipped RData file

[opetchey.zip](https://github.com/ReScience/ReScience-submission/files/201178/opetchey.zip)

**Comment by opetchey** [comment]
Yes, I still don't know why we're getting different results. But something to do with treatment of character variables.
In any case, I attempted a further improvement... see commit [860500c](https://github.com/ReScience/ReScience-submission/pull/15/commits/860500c99abe20d25505fe76311b948df8bb0889)

**Comment by yoavram** [comment]
**REVIEWER 1**

As far as I'm concerned and following what @tpoisot wrote above (31 Marh 2016) this is a minor issue. I believe the ms can be accepted.

**Comment by FedericoV** [comment]
I've been very busy but I will be able to handle this tomorrow.  Will
update and reproduce all the steps.

**Comment by opetchey** [comment]
@FedericoV Thanks. Please be sure to use the latest commit.

**Comment by FedericoV** [comment]
The last commit reproduces beautifully.  The report is also very well done - I don't use R at all, but I could follow almost all the steps/code.

I am satisfied with the paper in its current form.  The only minor comments I have is that I would be curious to know how come the results for the Lyapunov coefficients was slightly different, and the exact procedure through which the zeros were removed.

Also - another comment.  Is it possible to have within-document links?  For example, when you talk about (red line in Fig. S1b) it would be handy to have a link that brought you to the relevant figure immediately.

**Comment by tpoisot** [comment]
@FedericoV noted -- I think if @opetchey et al. have an idea, it can go in the ms. If not, since the differences are not really big, we can leave with this and move on to the next step.

As for the within-document links: maybe using `\autoref` in latex would work. But it can be fixed after we made the first decision.

**Comment by FedericoV** [comment]
Agreed completely.

**Comment by FedericoV** [comment]
@tpoisot I edited my first post here suggesting we accept this reproduction.  It's very well done, the code is very readable.  My suggestions are very minor and the reproduction is more than acceptable in its current form.

**Comment by tpoisot** [comment]
**EDITOR**

Accepted, April 13, 2016. Congratulations @opetchey _et al._ and thanks to @FedericoV and @yoavram 

@rougier , what is the next step?

**Comment by opetchey** [comment]
Excellent! Many thanks!

**Comment by rougier** [comment]
@tpoisot 

Next step is the actual publication but the procedure is not really smooth yet. If you have some time to try it and tell what's not clear (new issue)  that woudl be great ! Else I can do it.

The procedure is described at http://rescience.github.io/edit/ (see editing process). But mostly the goal is to freeze the repo (no more commit or only for obvious error), import it in the ReScience Archives (that will be the official repo) and modify the article such as to add editor/reviewers, change code/data repo links, set the volume (2) issue (1)

Once this done, you have to upload the archive to Zenodo (as journal article) and fill the the different fields (don't forget to add the editor field and volume/issue) and the link provided on the page above should make your upload part of the ReScience collection on Zenodo.

Last is to tell the original journal a replication has been published confirming the result, but I can do it.

**Comment by opetchey** [comment]
@tpoisot @rougier please let me know if I can or should help with any of these next steps.

**Comment by rougier** [comment]
Nothing is required from you right now. But on the other hand, you can join the board as reviewer if you're interested. Just let me know.

**Comment by rougier** [comment]
@tpoisot Do you want to handle the actual publication ?

**Comment by rougier** [comment]
I'll handle it.

**Comment by rougier** [comment]
@opetchey Can you give me the associated keywords ?

**Comment by tpoisot** [comment]
Yes, sorry about the delay -- was about to leave for a trip but a snow 
storm happened...

**Comment by rougier** [comment]
No problem. Does that mean you can handle the publication ?

**Comment by tpoisot** [comment]
I'd rather let you do it if you can, I'll be sure to look at what the 
different steps are.

**Comment by opetchey** [comment]
@rougier Yes, no problem. Keywords:
Ecology
Forecasting
Prediction
Chaos
Nonlinear dynamics
Plankton community
Species interactions

**Comment by rougier** [comment]
This submission has been accepted for publication, and has been published and will soon appear at 
http://rescience.github.io/read/

[DOI](http://dx.doi.org/10.5281/zenodo.50213)

**Pull request closed without merging**
