### PR TITLE
Review Request: Muellerklein

### PR DESCRIPTION
**Pull request by FlorianMuellerklein**
**Muellerklein**

Dear @ReScience/editors,

I request a review for the reproduction of the following paper:
- He, Kaiming, et al. "Identity mappings in deep residual networks." arXiv preprint [arXiv:1603.05027](https://arxiv.org/abs/1603.05027) (2016) 

and one result from
- Sergey Zagoruyko, Nikos Komodakis, "Wide Residual Neural Networks." arXiv preprint [arXiv:1605.07146](https://arxiv.org/abs/1605.07146) (2016)

I believe the original results have been faithfully reproduced as explained in the accompanying article.

Repository lives at https://github.com/FlorianMuellerklein/ReScience-submission/tree/muellerklein

---

**EDITOR**
- [x] Editor acknowledgment (@emmanuelle `03 July 2016`)
- [x] Reviewer 1 (@ogrisel `20 July 2016`)
- [x] Reviewer 2 (@ozancaglayan `24 August 2016`)
- [ ] Review 1 decision [accept/reject]
- [X] Review 2 decision [**accept**] `15 March 2017`
- [ ] Editor decision [accept/reject]

### CODE REVIEW

**Comment by FlorianMuellerklein** [comment]
**AUTHOR**

There are some formatting issues that I will resolve if this gets accepted.

**Comment by rougier** [comment]
**EDITOR-IN-CHIEF**

@emmanuelle Any update on this ?

**Comment by ogrisel** [comment]
@emmanuelle asked me to review this submission. I need to reinstall my GTX 980Ti to be able to run the code but hopefully I will do it in the coming week. Meanwhile @FlorianMuellerklein is there any change you want to include in the submission? What are the formatting changes you plan?

**Comment by FlorianMuellerklein** [comment]
@ogrisel I had some issues with the image sizes and some captions in the pdf that I need to fix. 

But, after submitting this pull request someone commented on my github repo that I might have a mistake in the projection shortcut. They said that the shortcut should take the preactivation as it's input. I think they may be correct, should I update my pull request or wait for reviewer input before changing anything? I linked to the issue on my repo below. 

https://github.com/FlorianMuellerklein/Identity-Mapping-ResNet-Lasagne/issues/2

**Comment by rougier** [comment]
@FlorianMuellerklein You can push your changes, they should be tracked here. For the formatting issues in the paper, I will handle it in the edition stage if accepted.

@ogrisel Thank you !

**Comment by ogrisel** [comment]
Please @FlorianMuellerklein feel free to push the changes. If you launch a series of new runs please report the new numbers in a new column in your tables so that we can track the impact of that change on the final validation error of the models.

**Comment by FlorianMuellerklein** [comment]
@ogrisel I pushed the changes so everything should be ready to go. I won't have time to check the new numbers for a little while (time to get some more GPUs) but I definitely will.

**Comment by ogrisel** [comment]
It seems that the submission misses a file:

```
Traceback (most recent call last):
  File "train_nn.py", line 92, in <module>
    train_X, test_X, train_y, test_y = load_pickle_data_cv()
  File "/home/ogrisel/code/ReScience-submission/code/utils.py", line 58, in load_pickle_data_cv
    np.save('data/pixel_mean.npy', pixel_mean)
  File "/home/ogrisel/.virtualenvs/py27/local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 477, in save
    fid = open(file, "wb")
IOError: [Errno 2] No such file or directory: 'data/pixel_mean.npy'
```

**Comment by FlorianMuellerklein** [comment]
@ogrisel That line should be saving the pre-pixel mean to be used to preprocess the testing data later on. I don't understand why it would give an error.

**Comment by ogrisel** [comment]
I ok I was in the wrong folder.

**Edit**: Actually no, when I run the script from the top level folder I get this other error:

```
$ python code/train_nn.py wide 16 4
Using gpu device 0: GeForce GTX 980 Ti (CNMeM is disabled, cuDNN 4007)
Using wide ResNet with depth 16 and width 4.
Traceback (most recent call last):
  File "code/train_nn.py", line 92, in <module>
    train_X, test_X, train_y, test_y = load_pickle_data_cv()
  File "/home/ogrisel/code/ReScience-submission/code/utils.py", line 19, in load_pickle_data_cv
    fo_1 = open('../data/cifar-10-batches-py/data_batch_1', 'rb')
IOError: [Errno 2] No such file or directory: '../data/cifar-10-batches-py/data_batch_1'
```

I believe the expectations wrt the folder structure have been broken when converting from the original repo to this submission PR.

**Comment by ogrisel** [comment]
Could you please extend the readme to to give the command line parameters to reproduce each of the score reported in the table. I guess those are:
- `python code/train_nn.py wide 16 4`
- `python code/train_nn.py  normal 110`
- `python code/train_nn.py  normal 164`

but it would be great if you could confirm this.

Also for the sake of reproducibility I think you should include the version number of the libraries you used (and the sha1 digest of the git repo for lasagne).

**Comment by FlorianMuellerklein** [comment]
@ogrisel Ok I'll update the README with the command lines and versions as soon as I can. 

The depth is actually the multiplier for how many residual blocks to insert between each downsampling layer. So for ResNet-110 and ResNet-164 depth=18 and for the wide residual network depth=2. 

`python code/train_nn.py wide 2 4`
`python code/train_nn.py normal 18`
`python code/train_nn.py bottleneck 18`

**Comment by ogrisel** [comment]
Thanks!

**Comment by ogrisel** [comment]
Ok I trained the "wide 2 4" configuration and could reach 0.957476 final validation accuracy. However the `weights` folder did not exist (probably because git does not checkout empty folders) so saving the weights failed. You might want to make sure to create the folders if they don't exists before writing files in this script :)

```
iter: 198 | TL: 0.192 | VL: 0.202 | Vacc: 0.956 | Ratio: 0.95 | Time: 157.3
iter: 199 | TL: 0.192 | VL: 0.2 | Vacc: 0.955 | Ratio: 0.96 | Time: 157.3
Final Acc: 0.957476
Traceback (most recent call last):
  File "train_nn.py", line 133, in <module>
    f = gzip.open('data/weights/%s%d_resnet.pklz'%(variant,depth), 'wb')
  File "/usr/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/usr/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: 'data/weights/wide2_resnet.pklz'
```

**Comment by FlorianMuellerklein** [comment]
@ogrisel Oh no, I'm really sorry about that. I'll add that to my next update. 

EDIT: Updated to include python package versions, commands to reproduce. train_nn.py now creates the necessary folders if they don't already exist.

**Comment by ogrisel** [comment]
I trained again a "wide 2 4" model and I got:

```
Accuracy on the testing set,  0.9513
```

So a 4.86% test error. This is significantly better than what you write in your report. Maybe because of d42627a452d1d5bb6c2d11f7dc2e2089213a557d?

I don't have the plot because of the matplotlib backend issue that I fixed in the mean time. You should probably store the train / val losses data into a file to decouple training from convergence monitoring but this is not a big deal. Here is the [text log of that run](a0e42f8e47414e98d40cdf0c1f1bb196) if you are interested.

Also it seems that 2 runs don't yield the same results despite the numpy rng seeding at the top of the script. I suspect that the init is done by the theano rng which is probably no seeded.

**Comment by ogrisel** [comment]
Another missing folder for the script to work by default: `plots`

```
Traceback (most recent call last):
  File "train_nn.py", line 150, in <module>
    pyplot.savefig('plots/%s%d_resnet.png'%(variant,depth))
  File "/home/ogrisel/.virtualenvs/py27/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 695, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/ogrisel/.virtualenvs/py27/local/lib/python2.7/site-packages/matplotlib/figure.py", line 1533, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/home/ogrisel/.virtualenvs/py27/local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2233, in print_figure
    **kwargs)
  File "/home/ogrisel/.virtualenvs/py27/local/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 521, in print_png
    filename_or_obj = open(filename_or_obj, 'wb')
IOError: [Errno 2] No such file or directory: 'plots/normal18_resnet.png'
```

**Edit** I had launched the run prior to your last change in 0134558. This specific issue should be fixed now. Please ignore this comment.

**Comment by ogrisel** [comment]
Here is the result of another run (this time ResNet-110): 

```
$ python train_nn.py normal 16  # ResNet-110
[...]
iter: 197 | TL: 0.159 | VL: 0.276 | Vacc: 0.943 | Ratio: 0.58 | Time: 347.6
iter: 198 | TL: 0.158 | VL: 0.28 | Vacc: 0.942 | Ratio: 0.56 | Time: 347.0
iter: 199 | TL: 0.157 | VL: 0.271 | Vacc: 0.943 | Ratio: 0.58 | Time: 346.8
Final Acc: 0.948774
$ python test_model.py normal 16
[...]
Accuracy on the testing set,  0.9385
```

So the test error for this run of ResNet-110 is 6.15% which is slightly better than the reported 6.37% in the Identity Mappings paper (median of 5 runs).

**Comment by FlorianMuellerklein** [comment]
@ogrisel Wow that is interesting that the wide ResNet did so much better, how close were the two runs with the wide net?

Your ResNet-110 is after my latest commit as well? As soon as I get some spare GPU time I will re-run these and update everything on my end.

**Comment by ogrisel** [comment]
My ResNet-110 run was run on the code as of d42627a. I don't have the weights of the first WRN run so I cannot compute its test accuracy.

**Comment by ogrisel** [comment]
@FlorianMuellerklein also: contrary to what the commit message says, the README file was not updated in  0134558.

**Comment by FlorianMuellerklein** [comment]
@ogrisel Whoops, I guess I forgot to add it to the commit. I'll fix that.

**Comment by ogrisel** [comment]
Here is the result for `ResNet-164` (trained with `python train_nn.py bottleneck 18` on d42627a as well) and interrupted at iteration 183 because the training loss was not moving much anymore:

```
Accuracy on the testing set,  0.9482
```

=> 5.180% test error which is better than the reported 5.46% error in the Identity Mappings paper.

Note that each iteration would take 639s on my GTX 980 Ti. This is much slower (4 times slower) than the 16 deep wide resnet and the GPU use is the 40-50% range rather than 80%+ for WRN which confirms what has been stated in the WRN paper.

**Comment by ogrisel** [comment]
I have very different speeds per-epochs than what you write in your report (for the preactivation resnets, the WRN speed is similar). I used Cuda 7.5 and CuDNN v4. Here is my `.theanorc`:

```
[global]
device=gpu
floatX=float32
allow_gc=True
optimizer_including="local_ultra_fast_sigmoid"

[nvcc]
use_fast_math=True
fastmath=True
```

What is yours?

**Comment by ogrisel** [comment]
I upgraded to CuDNN 5.1 RC and get the same speed.

**Comment by ogrisel** [comment]
I went back to a more streamlined theano configuration and still get the same speed per epoch:

```
[global]
device=gpu
floatX=float32
#allow_gc=True
#optimizer_including="local_ultra_fast_sigmoid"

#[nvcc]
#use_fast_math=True
#fastmath=True
```

**Comment by FlorianMuellerklein** [comment]
I'm using. 

```
[global]
mode=FAST_RUN
floatX=float32
device=gpu0
allow_gc=True
optimizer_including=cudnn

[dnn.conv]
algo_fwd=time_once
algo_bwd_data=time_once
algo_bwd_filter=time_once

[nvcc]
fastmath=True

[cuda]
root=/usr/local/cuda

[lib]
cnmem=0.45
```

**Comment by ogrisel** [comment]
Thanks, that was it. I now get a 90s epoch on the small WRN model as you reported. I should have read the theano doc. I think it's a good idea to include that info along with your CuDNN version in the report.

**Comment by ogrisel** [comment]
There is something that I don't understand w.r.t. the relation between the multiplier n and the depth of the resulting nets as described in the introduction of your article:

https://github.com/FlorianMuellerklein/ReScience-submission/blob/muellerklein/article/pre_and_wide_resnets.md#introduction

For resnets, the formula holds:

resnet-110 == d=16 x 2 conv x 3 block groups + 1 input conv + 1 output softmax
resnet-164 == d=16 x 3 conv x 3 block groups + 1 input conv + 1 output softmax

However for the WRN, n=2 would yield  2 \* 3 \* 2 + 2 == 14 which does not match any of the configurations (it should be 16 if I understand correctly). Where do the 2 missing layers come from?

**Comment by FlorianMuellerklein** [comment]
I noticed the same thing. They claimed that the only difference between WRN and the regular is that it's wider so I figured that it was a miscalculation on their part, most of their depths were off by two. Unless they added an extra residual block somewhere, but I couldn't find anything to indicate that.

**Comment by ogrisel** [comment]
The solution is to read their code then: https://github.com/szagoruyko/wide-residual-networks (I have not done it yet).

FYI I a currently running `train_nn.py wide 3 10` with your up to date version of the code. Each epoch is 370s long and the GPU usage is ~97% according to `nvidia-smi`.

**Comment by FlorianMuellerklein** [comment]
Unfortunately, I have and I still can't see where the two extra layers come from. Although I must confess that I'm not too familiar with Torch. 

They do however, have this `n = (depth - 4) / 6`. Which would make n=2 if you want depth of 16.

Also `train_nn.py wide 3 10` is huge! I look forward to seeing the performance, I couldn't go that big on my system.

**Comment by ogrisel** [comment]
I got 4.459% test error for `wide 3 10`. This is slightly worse than what was reported in the WRN paper (4.17% for d=28, k=10).

**Comment by FlorianMuellerklein** [comment]
That's unfortunate that the performance was worse. 

Next week I should have time to re-run all of my stuff and update the reported numbers in the submission.

**Comment by ogrisel** [comment]
Something to keep in mind: the experiments in the WRN paper are done on ZCA whitened data which is not the case in your version. That might also explain some discrepancies.

**Comment by FlorianMuellerklein** [comment]
Yes, I made that choice originally because I wanted to have a direct comparison to PreResNets. It seems like the results still mostly hold.

**Comment by FlorianMuellerklein** [comment]
Updated all my results with the bug fixes. New tables look like this. 

| **ResNet Type** | **Original Paper** | **Test Results** |
| :-: | :-: | :-: |
| ResNet-110 | 6.37 | 6.06 |
| ResNet-164 | 5.46 | 5.64 |
| WResNet-n2-k4 | 5.55 | 5.11 |

**Comment by ogrisel** [comment]
Good. I guess the differences are in the range of variability caused by different random seed init.

BTW, I understand the d = 6 \* n + 4 formula: it's the total number of conv layers, including the 3 projection layers + the first conv layer on the input. For 2 times 3x3 residual blocks in 3 residual groups you get 6 \* n conv 3x3 layers in the residual lane + 3 projection conv 1x1 layers on the shortcut lane + 1 time 3x3 conv layer on the input. Does that make sense?

**Comment by FlorianMuellerklein** [comment]
Yup, makes sense to me.

**Comment by rougier** [comment]
@emmanuelle Did you find/assign a second reviewer ?

**Comment by ozancaglayan** [comment]
Even the seed is fixed, there are at least one optimized GPU op in Theano which is non-deterministic,
And for the dnn.conv section of theanorc, the algorithms should be set to `deterministic` or `fft`.
Both are discussed in https://github.com/Theano/Theano/issues/3029

**Comment by ozancaglayan** [comment]
Also, I can be the 2nd reviewer if you'd like to.

**Comment by rougier** [comment]
@ozancaglayan That would be great if you can review the paper !

**Comment by ozancaglayan** [comment]
@FlorianMuellerklein 
I think there's still a conflict between `../data/cifar-10-batches-py/` and `os.mkdir('data/weights')` calls. First assumes we're inside `code` while the second in the root directory.

EDIT:
There's also the problem that the batches provided by the repo are under `data` without `cifar-10-batches-py` prefix while `utils.py` tries to load them using `../data/cifar-10-batches-py`

I'm facing every folder structure problem previously reported by @ogrisel so I think you did not fix those problems, right?

**Comment by ogrisel** [comment]
I think I ended up creating a bunch of subfolders in the code directory and launch the main script from there to get it to work.

**Comment by FlorianMuellerklein** [comment]
Sorry about these folder issues. This started out as a personal project of mine and I later wrote it up as a paper. If it would help I could write a bash script to create a bunch of folders and go through and make sure that everything is being loaded from the correct places.

**Comment by ozancaglayan** [comment]
Fine for me but I suppose that after the reviewing process the `code` folder should run out-of-the-box :)

**Comment by FlorianMuellerklein** [comment]
@ozancaglayan No problem, I'll make sure that I update it to run out of the box once the reviewing is over.

**Comment by emmanuelle** [comment]
thank you very much @ogrisel and @ozancaglayan !

**Comment by ozancaglayan** [comment]
So I finally finished training the 3 models mentioned. Below are the results on Test Set using `test_model.py`. I believe your results in your rescience paper are also for the test set right?

| ResNet Type | Original Paper | Reported in Rescience Article | Reviewer 1 | Reviewer 2 |
| --- | --- | --- | --- | --- |
| ResNet-110 | 6.37 | 6.06 | 6.150 | 6.189 |
| ResNet-164 | 5.46 | 5.64 | 5.180 | 5.820 |
| WResNet-n2-k4 | 5.55 | 5. 11 | 4.86 | 4.73 |

**Comment by ogrisel** [comment]
@ozancaglayan I went on and consolidated my own results that were scattered in the previous comments into your summary table.

I think the variation is entirely attributable to the the random init of the weight. The original pre-activation resnet paper did a median of 5 runs which makes me think that the reproduced test scores are inline. The standard deviation is quite high though: in the order of half a percent I would say.

The reproduced WResNet-n2-k4 test scores seem slightly better that the original paper.

**Comment by ozancaglayan** [comment]
Ah I actually fixed the seed to 1234, used deterministic CUDNN ops in theanorc, and my Theano is also patched to be more deterministic on GPU.

**Comment by rougier** [comment]
@ogrisel @ozancaglayan Any update on the review ?

**Comment by rougier** [comment]
@ogrisel @ozancaglayan 🔔 Any update on the review ?

**Comment by ozancaglayan** [comment]
Should we comment on the layout or typography issues in the article?

**Comment by rougier** [comment]
Yes, you can signal them. Note that @FlorianMuellerklein signaled at the top there were some formatting issue. But it would be great if you can report them here. @FlorianMuellerklein can correct most of them hopefully and I will correct others during publication.

**Comment by rougier** [comment]
@ogrisel @ozancaglayan 🔔

**Comment by rougier** [comment]
Dear @emmanuelle @ogrisel @ozancaglayan,

Is there anything we can do to have this review to move forward ?

**Comment by rougier** [comment]
Dear @emmanuelle @ogrisel @ozancaglayan,

Any update on this review ?

**Comment by ozancaglayan** [comment]
Sorry for the delay, I am really busy these days.

## Code
- [ ] There were some issues previously mentioned by me and @ogrisel about the folder mess. It would be nice if the code once cloned works out-of-the-box for maximum reproducibility.
- [ ] Fixing the numpy rng seed can be good for improved reproducibility but this may change your reported results.

## Article
- [ ] In the first paragraph, the sentences starting with "main idea", "basic idea" and "the residual blocks are basically" should be reformulated/merged for ease of reading.
- [ ] The first figure can be enhanced with a higher resolution one. The caption of the figure is not positioned correctly.
- [ ] "Whenever the number of filters are increased **[comma here]** the first convolution layer..."
- [ ] First sentence after the first table should be the caption of the table or it should be a bold title, etc.
- [ ] The next sentence there is problematic. What is parallel to what? By saying "are added after each block", do you mean "are summed"?
- [ ] The next paragraph, you can say "[1] also introduces a bottleneck architecture" instead of mentioning the full article name
- [ ] When you cite the papers inside brackets in the whole article, I think they should be before the final dot of the sentence, e.g. "foo bar [1]." instead of "foo bar. [1]"
- [ ] Preactivation Residual Networks [2] and Wide Residual Networks[3] may be better than "... [2][3]"
- [ ] Figure title for preactivation resnet is not positioned correctly.
- [ ] The tables need captions for clarity.
- [ ] Paragraph is wrongly wrapped with the figure showing basic-wide and wide-dropout blocks.
- [ ] I think there's no need to put a quoting from an article inside quotes since you cite it just after the sentence. An example is from the Methods section: "32x32 images, with the per-pixel mean subtracted" [1] 
- [ ] Data Augmentation last sentence suggestion: "Batch size of 64 is used instead of 128 because of hardware constraints."
- [ ] Training and Regularization: The learning rate schedule between the curly braces can be explained textually for clarity.
- [ ] Hardware and software last sentence -> "but **with** more memory"
- [ ] Results last paragraph: "...in the cross-entropy during training and also much less of a quadratic trend than seen in other neural networks." is not very clear to me.

**Comment by rougier** [comment]
@FlorianMuellerklein Can you make the suggested modification ?
@ogrisel @ozancaglayan What is you decision, does the paper needs more review or can you make a decision about acceptation/rejection ?

**Comment by ozancaglayan** [comment]
Should I wait for the modifications to decide?

**Comment by rougier** [comment]
No, but you can condition your decision (e.g. provided the author makes the suggested changes...)

**Comment by FlorianMuellerklein** [comment]
@rougier Sorry, I've been pretty busy lately as well. I'll have these edits soon.

**Comment by ozancaglayan** [comment]
OK, provided the author makes the suggested changes, my decision is to accept the paper.

**Comment by rougier** [comment]
@ogrisel Can you tell you decision about the paper or do you need more time ?

**Comment by rougier** [comment]
Dear @FlorianMuellerklein @ogrisel @emmanuelle @ozancaglayan,

This submission is now 6 months old and we need to try to move things forwards.
Could you have a look at past messages and possibly answer questions?  Thanks.

**Comment by rougier** [comment]
🛎 @FlorianMuellerklein @ogrisel @emmanuelle @ozancaglayan,

**Comment by FlorianMuellerklein** [comment]
I just pushed an update with most of the changes that Ozan requested.

**Comment by rougier** [comment]
@FlorianMuellerklein Thanks for the update!
@ozancaglayan Can you make your decision based on the new update?

**Comment by rougier** [comment]
@ReScience/reviewers We need some new reviewers here if anyone interested!

**Comment by ozancaglayan** [comment]
As I mentioned before, I accept the paper.

**Comment by rougier** [comment]
@ozancaglayan Sorry, I didn't see it.

**Comment by rougier** [comment]
🛎 @grisel  Can you tell me if you're able to handle this review or if we need to look for another reviewer ? No problem if you can't but I need to know to try to move this review forward.

**Comment by ctb** [comment]
bump @grisel.

**Comment by rth** [comment]
> :bellhop_bell: @grisel Can you tell me if you're able to handle this review or if we need to look for another reviewer ? No problem if you can't but I need to know to try to move this review forward.

With an "o" @ogrisel ..

**Comment by ogrisel** [comment]
Sorry for the lack of reply. I will try to find some time next week do review the updated paper / code.

**Comment by remram44** [comment]
It seems that this uses an unreleased version of Lasagne (which requires a development version of Theano as well). It would be great if the precise Git hashes used to run this could be included in the README. I applaud your including the precise version of numpy and Theano, but you left out sklearn and matplotlib as well.

The `pip freeze` command might help!

**Comment by rougier** [comment]
@FlorianMuellerklein Are you still following this submission ? We might need to assign a new reviewer to complete the process but first I wanted to know if you're still interested.

**Comment by FedericoV** [comment]
If @FlorianMuellerklein is not available, I can jump in - but not sure if it's ideal to have an additional pair of eyes at this point in the process.

**Comment by rougier** [comment]
Thanks @FedericoV. @FlorianMuellerklein is the author of the replication. @ozancaglayan alread accepted the paper and @ogrisel has not responded yet. At this point, if you can review it, that would be great.

**Pull request closed without merging**
