### PR TITLE
Tallec Blier Kalainathan 2019

### PR DESCRIPTION
**Pull request by leonardblier**
**AUTHOR**

Dear @ReScience/editors,

I request a review for the following replication:

### Original article

**Title:Recurrent World Models Facilitate Policy Evolution**
**Author(s):David Ha and Jürgen Schmidhuber**
**Journal (or Conference):Conference on Neural Information Processing Systems (NeurIPS)**
**Year:2018**
**DOI:**
**PDF:http://papers.nips.cc/paper/7512-recurrent-world-models-facilitate-policy-evolution.pdf**

### Replication

**Author(s)**: Corentin Tallec (*), Léonard Blier (*), Diviyan Kalainathan
**Repository**:https://github.com/leonardblier/ReScience-submission/tree/Tallec-Blier-Kalainathan-2019/code
**PDF**:https://github.com/leonardblier/ReScience-submission/blob/Tallec-Blier-Kalainathan-2019/article/Tallec-Blier-Kalainathan-2019.pdf
**Keywords**: Machine Learning, Reinforcement Learning, Model based RL
**Language**: English
**Domain**: Machine Learning

### Results

* [ ] Article has been fully replicated
* [x] Article has been partially replicated
* [ ] Article has not been replicated

### Potential reviewers

---

**EDITOR**

* [x] Editor acknowledgment (@oliviaguest, `27-02-2019`)
* [x] Reviewer 1 (@qihongl, `22-04-2019`)
* [x] Reviewer 2 (@costashatz, `17-05-2019`)
* [ ] Review 1 decision [accept/reject]
* [ ] Review 2 decision [accept/reject]
* [ ] Editor decision [accept/reject]

### CODE REVIEW

**Comment by rougier** [comment]
Thanks for your submission, an editor will soon be assigned. In the meantime, can you edit your post (https://github.com/ReScience/ReScience-submission/pull/55) to add a link to your code repository and PDF?

**Comment by rougier** [comment]
@oliviaguest Could you handle this submission?

**Comment by rougier** [comment]
Thanks! @leonardblier, @oliviaguest will handle your submission but we still need a link to your code and your PDF.

**Comment by leonardblier** [comment]
Thank you @rougier and @oliviaguest.
I have just updated my post and added the links.

**Comment by oliviaguest** [comment]
I will starting looking for reviewers once the code/PDF are uploaded.

**Comment by oliviaguest** [comment]
@leonardblier No idea why your previous comment didn't show up to me. Maybe I should refresh my browser tabs more. :laughing: Thank you!

**Comment by oliviaguest** [comment]
@leonardblier Am I correct in thinking that "Article has been fully replicated" is the correct option from above?

**Comment by oliviaguest** [comment]
@ozancaglayan @qihongl would you be interested/available?

**Comment by leonardblier** [comment]
Actually, the article has been partially replicated. We reproduced the Carracing experiment (section 3 of the original paper), but we did not reproduce the experiments in the VizDoom environment (Section 4 of the original paper). I selected the corresponding option in the form above.

**Comment by rougier** [comment]
@oliviaguest Bi-weekly gentle reminder (or something like that)...

**Comment by oliviaguest** [comment]
@rougier shall I try other reviewers?

**Comment by rougier** [comment]
Yes. In the meantime you can try to contact @ozancaglayan and @qihongl by mailm (some people have mail notification disabled and do not check notification online too often)

**Comment by rougier** [comment]
@oliviaguest Gentle reminder

**Comment by qihongl** [comment]
Hi Folks! Sorry, I completely overlooked this PR…  I like Ha & Schmidhuber (2018) a lot, and I'm happy to take a look!

**Comment by ozancaglayan** [comment]
Hello. Although I receive the notification emails, I think I have to reduce it to only the ones that mentions me to not miss these.. Sorry. I am very busy writing my thesis these days, I can only take a look around June/July.

**Comment by qihongl** [comment]
@ozancaglayan yes I'm googling how to do that right now lol

**Comment by oliviaguest** [comment]
@ozancaglayan I am asking others, so please focus on the thesis and if I find nobody or you end up having time, we can always regroup and you can let us know if you are available. Good luck and thanks!

**Comment by qihongl** [comment]
Hi Folks, sorry about the delay! I will try to get back to this next week!

**Comment by qihongl** [comment]
@leonardblier 

So far I tried osx and linux, and it seems that `box2d` is often an issue when I `pip install requirements.txt` (`Failed building wheel for box2d`). With some googling, I can get it to work, but I think it would be nice if the installation part can be made easier. 

Or am I doing anything incorrectly? I created a new conda with python 3.7 tried pip install. And here's the error message: 
https://gist.github.com/qihongl/a5fb1610ae8f73c0611a76438e4f57ee#file-resci-tbk19-err-L71

**Comment by qihongl** [comment]
@leonardblier 
btw is the code intended to be used on Ubuntu only? I think `data/generation_script.py` is specific to Ubuntu.

**Comment by qihongl** [comment]
I still haven't tried all of the code. Based on the paper, I think this work is awesome! Many people would be interested in a clean pytorch implementation of Ha & Schmidhuber (2018), including me :)

Some minor thoughts: 
1. It would be nice if the learning curve figure contains a pointer to the original reference, such as "this qualitatively replicates fig. 4 left from Ha & Schmidhuber (2018)"? And I guess the unit of the x-axis of your figure is different from the figure in the original paper? Is it possible to use the same unit or explain the conversion rule (between the two figures)? 

2. Is the sample size of your experiment reported somewhere? 

3. I guess the \ref{} to figure and tables will be fixed later on? 

4. The experiments on random network are interesting. If you think this is related to the echo state network, or reservoir computing (http://www.scholarpedia.org/article/Echo_state_network), it might be useful to add a pointer/reference to those works? Some readers might be interested in reading about those works further. I am not familiar with that topic, so I don't know what's a good representative reference. 

Thank you very much again for sharing your work!

**Comment by qihongl** [comment]
And I just ran some code checks: 

1. In `eval_controller.py`, `pdb` is imported but unused. 

2. In `check_rollouts.py`, `trainmdrnn.py` and `utils/learning.py`, you have `# WARNING : THIS SHOULD BE REPLACE WITH PYTORCH 0.5`, what does that mean? Is this fixable?

**Comment by costashatz** [comment]
Hello @oliviaguest and all! I'd be happy to review this submission. I'll try to start in about 10 days to do so..

**Comment by oliviaguest** [comment]
@leonardblier @ctallec can you fix the merge conflict please? :smiley_cat:

**Comment by ctallec** [comment]
@qihongl, thanks for accepting to review our work ! We've pushed a patch to the pull request to try and attend your concerns. Here are some details regarding what we did:
- The requirements should now be up to date. There might still be issues with pytorch when using GPUs, since it depends on the CUDA version that is available on the machine you are using.
- We've removed the pdb import.
- We've fixed the Warnings related to torch 0.5 (this was simply a piece of code that was not yet available in the production version of pytorch when we first released the code and that we had to add manually).
-I've added the pointer to the original figure, as well as an explanation on the x-axis (they do correspond, but we had to limit the number of generations due to compuational limitations).
-References to figures should be fixed.
- We've added a reference to _Jaeger, H. (2002). Tutorial on training recurrent neural networks, covering BPPT, RTRL, EKF and the" echo state network" approach (Vol. 5). Bonn: GMD-Forschungszentrum Informationstechnik._ which is, to us, one of the best piece of information on ESNs.
- the code is indeed only expected to work without further tuning on a linux distribution, and was only tested with Ubuntu. I can add this to the README if you want me to. Thanks for pointing this out !
- Which sample size are you referring to ? The number of training examples for the VAE and MDRNN ?

@oliviaguest the merge conflict should be fixed.

**Comment by leonardblier** [comment]
Hi @oliviaguest !
Are you sure that this PR should be merged on master? I am afraid this could be a mistake since the review process is not finished here.

**Comment by oliviaguest** [comment]
@leonardblier ugh, oops. @rougier did I just make a mess? :sweat_smile:

**Comment by rougier** [comment]
Yep, I think so... can you "unmerge" (no, I don't know how to do it...)

**Comment by rougier** [comment]
https://help.github.com/en/articles/reverting-a-pull-request

**Comment by oliviaguest** [comment]
OK, I think I fixed it?

**Comment by rougier** [comment]
I still have the merged tag at the top, I'm not sure if it worked.

**Comment by rougier** [comment]
@ReScience/editors to the rescue... 
Does anyone know how to re-open a PR request that was (wrongly) merged then cancelled ?

**Comment by khinsen** [comment]
@rougier How much of a problem is this? Just aesthetics (the "merged" label on top of the page)? We can always do the "real" final merge from the `git` command line. Is there any other functionality we need and don't have any more?

**Comment by pdebuyl** [comment]
Hi @rougier I believe that it is not possible. I had the issue already and had to open a new PR. Else, as @khinsen writes you can keep this PR as is and use git.

**Comment by rougier** [comment]
Ok then.

**Comment by qihongl** [comment]
@ctallec Thank you very much for the updates! I will try to run everything again week!

By sample size,  I was referring to the error bar for fig 2. Is that some standard error across different models (trained from random seeds)? I was curious about how many models contributed to each curve.

**Comment by costashatz** [comment]
@ctallec @leonardblier Thank you very much for this submission! You chose a very interesting paper to re-produce..

I will give a more detailed look in the code (although it looks good) in the following days, but here are a few more general comments:

- Why didn't you replicate the some of the doom experiments of the paper? It seems that the pipeline is there. I could not find an answer in your submitted description. It'd be nice to elaborate on this one..
- I liked a lot the extra experiments that give useful insights on the success of the approach. One experiment that I would like to see is a more classical model-based RL pipeline but using the same model learning technique:
    a) Use a random policy and perform a few random episodes (much less than the number you are using now, e.g. 50 episodes)
    b) Learn the models (VAE, MDN-RNN) as is with all the data gathered so far
    c) Optimize the policy parameters with CMA-ES (initialize parameters to previous best)
    d) Apply the optimized policy on the environment for a few episodes (the same number as in a, e.g., 50 episodes)
    e) Go back to b) until some criteria is met (e.g., max number of episodes)

This would be a very meaningful extra experiment as using just random episodes was the main criticism of the approach (see for example [this tweet](https://twitter.com/shimon8282/status/979344417961250817?s=20) from Shimon Whiteson). It seems to me that the whole pipeline is there to implement this comparison and this would actually be a very valuable information to have..
- Figure 2 in your paper mentions that is a replication of Figure 4 of the original paper. I cannot find a Figure 4 in the original paper. Moreover, what are the dotted lines in Figure 2?

Thank you very much again for sharing your work!

**Comment by qihongl** [comment]
Hi, Folks 

@ctallec I tried running your code. It seems that training models take quite a while. Can you provide some rough run time estimates based on your specs? I think I need to launch jobs on the university clusters. 

Thank you very much!

**Comment by oliviaguest** [comment]
@ctallec @leonardblier 🔔 please see above — thanks!

**Comment by oliviaguest** [comment]
@rougier I am thinking this might be abandoned. 😞

**Comment by ctallec** [comment]
Hi Olivia, Qihongl and Costahatz,

First of, let us deeply apologize for the delayed answer, it's been a very busy
summer. 

We would like to thank both reviewers for the time they took reviewing our reproduction,
In what follows we will try to answer most of your remarks/questions.

@costashatz About the doom experiments: Indeed, the pipeline is there, but
adding these experiments would still be computationally expensive, because of
the controller's training. Our main objective when doing this reproducibility
project was to investigate the role of the World Model part. Our experiments
with a random RNN gave very surprising results. Thus we decided that sharing
this work was interesting, and that replicating the results on the Doom
environment would have limited added value.

On the training loop proposed by @costahatz, this is indeed a direction we
considered. However, given that the agent already achieves good (nearly
optimal) performance without the need to regenerate new rollouts with partially
trained policies, we do not expect this process to improve results by a lot.
Testing the improvement obtained using this kind of training procedure would
probably require us to move to more complex environments, which is out of the
scope of this replication.

Figure 4 is in the original paper appendix, and is indeed not displayed in the
paper version we gave, but is available at
https://arxiv.org/pdf/1809.01999.pdf. The dotted lines show the performance of
the top performer in the population. This is mentionned in the text, but we can
move this information in the legend if you want us to.

@qihongl, for estimated runtimes, both VAE and MDRNN training should be quite
fast (we used a pretty stringent stopping condition, but even if you stop
training after 10 or 15 epochs, both models should be good enough to provide
good results, running it until the end will ensure replication but take a bit
more time. With our setting, it took less than one day to train both the VAE
and MDRNN). For the controller training, the training process is much longer,
and we trained for approximately 4 days before reaching the presented results.

Sorry again for the delay.

**Comment by rougier** [comment]
@oliviaguest It's live again.

**Comment by costashatz** [comment]
@ctallec @leonardblier thanks for the reply!

> Figure 4 is in the original paper appendix, and is indeed not displayed in the
> paper version we gave, but is available at
> https://arxiv.org/pdf/1809.01999.pdf. The dotted lines show the performance of
> the top performer in the population. This is mentionned in the text, but we can
> move this information in the legend if you want us to.

Sorry about this. Didn't realize that you gave a specific version. Yes you can say it one more as a footnote for better coverage. Thanks!

> Thus we decided that sharing
> this work was interesting, and that replicating the results on the Doom
> environment would have limited added value.

I am not sure if I agree with this statement. The Doom environment is more complex than the CarRacing one and would give much better insights about the role of both the World Model (maybe the random RNN does not work very well there for example!) and the whole algorithm itself.

> However, given that the agent already achieves good (nearly
> optimal) performance without the need to regenerate new rollouts with partially
> trained policies, we do not expect this process to improve results by a lot.

This is because the environment you are dealing with (CarRacing) is quite simple. But also because I meant something different. What we care about (in what I said) is the learning curve: that is, how much we improve as we acquire new data. Of course, in a simple environment, a lot of random data might be enough to learn the optimal policy. But even in this case, if you do not just select random data, but you are optimizing for them (in smaller batches) the learning curve could be much steeper and thus in the end we learn the task in much fewer time-steps.

> Testing the improvement obtained using this kind of training procedure would
> probably require us to move to more complex environments, which is out of the
> scope of this replication.

I again disagree with this statement. As I explained above, even simple systems can showcase the difference of learning algorithms. In our case, I might agree with you that CarRacing is too simple, but then it's questionable whether any conclusion for the model learning part is valuable (this might be the reason why the random RNN performs quite well also). However, I believe that the CarRacing environment is not TOO simple (I mean the cart-pole swing-up task has been a benchmark for several decades and it's simple) and we should be able to make draw some nice conclusions about the training loop that I suggested.

Overall, I believe that either the Doom environment must be implemented or the training pipeline that I suggested for the CarRacing environment. Otherwise, it seems like a half-replication of the paper to me.

Thanks for the good work and sorry for the delay on my answer!

**Comment by oliviaguest** [comment]
@leonardblier can you update me as to what you are working on for this, please? :smile:

**Comment by oliviaguest** [comment]
@rougier this is moving very slowly still... do you have any ideas how to make this move along faster?

**Comment by rougier** [comment]
@oliviaguest I dropped  @leonardblier and @ctallec an email (with you in CC). Maybe they do not have email notifications and don't visit GitHub too often. If we don't get news by the end of next week, I think we can close the PR and re-open it if necessary.

**Comment by oliviaguest** [comment]
@rougier thank you — perhaps they are just very busy... so yes, we can re-open in the future with a timeline from them so we don't keep having this issue?

**Comment by leonardblier** [comment]
Dear editors and reviewers,

We deeply apologise for the delayed answer. We have indeed be very busy, and since the reviewers asked for additional results which require both a significant amount of engineering and computationally expensive experiments, we needed time before starting to work on it. We will now reply faster, and upload in the next weeks an updated version of the paper.

@costashatz Thank you for your answer, we understand your remarks. Our point was not that the additional experiments you are proposing would not be useful, but rather that our experiments were already adding significant value to the original paper, both on its reproducibility and on the impact of the world model.

We are in the process of implementing some of the additional experiments you are suggesting.

We will at least perform the experiments on the CarRacing environment with the modified training loop, by applying the optimized policy for a few episodes instead of using only rollouts from the random policy.

For your second point, while the CarRacing environment is relatively easy to install and experiment with, we are running into some installation and configuration problems with the Doom environment. Getting this to work will probably make this part, if not the whole project, much harder to reproduce. Concretely, we are currently having trouble with two aspects of the reproduction:
1. The Doom wrapper used by the original author of the paper seems to conflict with Ubuntu 18.04, using it will make the project reliant on a specific Ubuntu version and hurt reproducibility.
2. The Doom environment seems to conflict with our naive way of running environments in parallel, even for rollout generation. This would mean either going back to a sequential approach (which will make the rollout generation quite slow), or trying to implement a distribution method compatible with the environment, which will probably hurt the readability of the code.

We thank you again for your useful remarks, and will try to come back with new results as soon as possible.

**Comment by costashatz** [comment]
> We will at least perform the experiments on the CarRacing environment with the modified training loop, by applying the optimized policy for a few episodes instead of using only rollouts from the random policy.

Great! This would be enough for me! Waiting for your reply!

> Getting this to work will probably make this part, if not the whole project, much harder to reproduce. Concretely, we are currently having trouble with two aspects of the reproduction:

This is okay. For me it would be okay to just have the modified loop with the CarRacing environment..

**Comment by oliviaguest** [comment]
@leonardblier that is OK but perhaps set out a rough timeline for us? If you expect to be busy, it would help.

**Comment by leonardblier** [comment]
@costashatz  Thank you for your answer! I am working on it.

@oliviaguest I have just started to implement the new experiments. The experiments are quite long, so I would expect all of them to be finished and the new version of the paper to be uploaded before Christmas.
Thank you again for your patience!

**Comment by leonardblier** [comment]
Dear editors and reviewers,
Just to keep you updated, we have finished to run the additional experiments. We will update the text and the code, and I expect the new version to be pushed before the end of next week.

**Comment by leonardblier** [comment]
Dear editors and reviewers,
We have just pushed a new version of the paper, containing the new experiments. 
Since the PR is closed, it seems that the last commits are not available in the PR interface. Everything can be found in the fork: [github.com/leonardblier/ReScience-submission/tree/Tallec-Blier-Kalainathan-2019](https://github.com/leonardblier/ReScience-submission/tree/Tallec-Blier-Kalainathan-2019)
The link to the pdf at the top of the PR is still working: [github.com/leonardblier/ReScience-submission/blob/Tallec-Blier-Kalainathan-2019/article/Tallec-Blier-Kalainathan-2019.pdf](https://github.com/leonardblier/ReScience-submission/blob/Tallec-Blier-Kalainathan-2019/article/Tallec-Blier-Kalainathan-2019.pdf)
Thank you again for your patience!

**Comment by oliviaguest** [comment]
@qihongl @costashatz please see above. :point_up:

**Comment by costashatz** [comment]
@leonardblier @ctallec Thank you for the updated experiments/paper.

I am very happy with the new results and experiments. This makes the reproduction of the approach much more powerful.

I have only a few minor comments:
   - Figure 2 is a bit fuzzy. For the new experiments (pipeline), this is a bit weird since you should run CMA-ES multiple times. Can you explain in a bit more details the new algorithm (pipeline) and how we should interpret Figure 2?
   - How are you re-training the models using the new data acquired (in the pipeline again)? Are you using just the new data? Or using all the previous data also? I would use all the previous data.
   - One plot that is missing is the following: interaction time over performance. For the experiments of the original paper, this would be a static line, since all the data are gathered once. But for the pipeline this should be more insightful.
   - One last point connected to the previous ones: are you using the same initial random points for the pipeline? I would use much fewer initial random points, and then periodically collect more data points (and use all gathered points to train the models; see above). In addition, I would let CMA-ES converge everytime I collect new data points and learn new models. Then I would apply the converged policy a few times on the system, collect new data, re-learn the models, and then optimize again with CMA-ES with the new model.

Overall I like the new version more, but we need a few more explanations about what's going on. Also, if you didn't (as I described above; this is fuzzy), I would like to see the traditional model-based policy search pipeline:
       1) Run a few random behaviors on the system
       2) Learn the models with all the gathered data
       3) Optimize the policy on the models (here using CMA-ES)
       4) Run a few times the optimized policy on the system
       5) Go back to 2 until some convergence criteria is met

Thanks a lot!

**Pull request merged**
