### PR TITLE
Cressot coninx merckling perrin doncieux 2019

### PR DESCRIPTION
**Pull request by Lcressot**
**CRESSOT-CONINX-MERCKLING-PERRIN-DONCIEUX**  

Dear @ReScience/editors,

I request a review for the following replication:

### Original article

**Title:** Learning state representations with robotic priors  
**Author(s):** Jonschkowski, R. and Brock, O.  
**Journal (or Conference):** Autonomous Robots,39(3), pp.407-428  
**Year:** 2015  
**DOI:** http://dx.doi.org/10.1007/s10514-015-9459-7   
**PDF:** http://www.robotics.tu-berlin.de/fileadmin/fg170/Publikationen_pdf/Jonschkowski-15-AURO.pdf   

### Replication

**Author(s):** Cressot L., Coninx A., Merckling A., Perrin N., Doncieux S.   
**Repository**:  [code](https://github.com/Lcressot/ReScience-submission/tree/CRESSOT-CONINX-MERCKLING-PERRIN-DONCIEUX-2019/article)
**PDF**:  [article.pdf](https://github.com/Lcressot/ReScience-submission/blob/CRESSOT-CONINX-MERCKLING-PERRIN-DONCIEUX-2019/article/CRESSOT-CONINX-MERCKLING-PERRIN-DONCIEUX-2019.pdf)
**Keywords**:  State representation learning, priors, robotics
**Language**:  python 3
**Domain**:  machine learning / robotics

### Results

* [ ] Article has been fully replicated
* [X] Article has been partially replicated
* [ ] Article has not been replicated

### Potential reviewers

Olivier Grisel
Max M. Losch
Xuedong Shang
Rui Portela
Josh Gardner
Inderdeep Singh Bajwa

---

**EDITOR**

* [x] Editor acknowledgment (@rougier, `January 25, 2019`)
* [x] Reviewer 1  (@thmosqueiro `January 28, 2019`)
* [X] Reviewer 2 (@jpgard `January 29, 2019`)
* [ ] Review 1 decision [accept/reject]
* [ ] Review 2 decision [accept/reject]
* [ ] Editor decision [accept/reject]

### CODE REVIEW

**Comment by Lcressot** [comment]
Hi,
There seem to be an issue with the compilation with .md and .tex, so I changed the Makefile to compile in .tex only

**Comment by rougier** [comment]
@Lcressot I think some (critical) information is missing from your initial PR. Can you edit it to add a link to your repository and PDF?

**Comment by pdebuyl** [comment]
Also, @Lcressot you must edit *only* the `.md` file. The `.tex` file is considered intermediate at ReScience. We need the `.md` file for other possible representations of the article (html, for instance).

**Comment by Lcressot** [comment]
Hi,

Sorry I didn’t understand what repository do I need to include to the PR (The rescience repository itself ?).
And concerning the pdf, do you mean a link to the overleaf editing repository ?

Thank you very much !
Loic Cressot

**Comment by rougier** [comment]
If you read your first post, there is no text for `repository` and `PDF` (under replication). This means we don't know where is your code and where is your article. Can you add them (either edit your first post or give the link in your answer and I'll edit the post)

**Comment by rougier** [comment]
@Lcressot We still need the address for your PDF and code repo 😄

**Comment by Lcressot** [comment]
Hi,
I am sorry but I don’t get what’s wrong.

Both my code and article are available at : https://github.com/Lcressot/ReScience-submission/tree/CRESSOT-CONINX-MERCKLING-PERRIN-DONCIEUX-2019/article <https://github.com/Lcressot/ReScience-submission/tree/CRESSOT-CONINX-MERCKLING-PERRIN-DONCIEUX-2019/article>

I heard there was currently problems with .md file compilations and thus I changed the Makefile so that it produced my pdf only with .tex.
I have no other repo for the code and regarding the pdf it on an overleaf repository (is it the link you want ?).

Please tell me what I am getting wrong and excuse me in advance !

Cordially,
Loic Cressot

**Comment by rougier** [comment]
Now it's fine. Maybe you get notification by mail and do not see the actual thread at https://github.com/ReScience/ReScience-submission/pull/54. Your initial comment lacked the link to your article and your code repository. But now that you've provided the link, I've edited your initial and review can begin. Sorry for the trouble.

**Comment by rougier** [comment]
Last thing, you might have forgotten to run bibtex or biber. References are missing from the pdf.

**Comment by rougier** [comment]
@ogrisel, @benureau, @mlosch, @xuedong, @thmosqueiro Coudl your review this replication of "Learning state representations with robotic priors" ?

**Comment by Lcressot** [comment]
Hi,
Thank you for your help and sorry for the inconvenience.

I couldn’t run the pdf entirely myself because I lacked some package and I hoped you could build it yourself with the Makefile.
You can also find in this email the pdf built on overleaf, which should contain all reference. I can also push it if you want.

Thanks again !
Loic

**Comment by rougier** [comment]
Upload the overleaf PDF on your github repo and I will modify the link (attached PDF didn't go through the GitHub filter)

**Comment by Lcressot** [comment]
Hi,

I pushed the pdf with the correct refs on the github repo available here : https://github.com/Lcressot/ReScience-submission/blob/CRESSOT-CONINX-MERCKLING-PERRIN-DONCIEUX-2019/article/CRESSOT-CONINX-MERCKLING-PERRIN-DONCIEUX-2019.pdf <https://github.com/Lcressot/ReScience-submission/blob/CRESSOT-CONINX-MERCKLING-PERRIN-DONCIEUX-2019/article/CRESSOT-CONINX-MERCKLING-PERRIN-DONCIEUX-2019.pdf> 

Thanks and sorry again !!

cheers,
Loic Cressot

**Comment by thmosqueiro** [comment]
Checking in. @rougier, sure I can review this. What's the expected timeline?

**Comment by rougier** [comment]
@thmosqueiro One month would be nice but it can be longer if you need more time. I'm waiting for the second reviewer and then we can start.

**Comment by rougier** [comment]
@jpgard Could you review this submission (keywords: state representation learning, priors, robotics)

**Comment by jpgard** [comment]
@rougier yes I can review. Is there a set of reviewer guidelines/procedures you could share a link to?

**Comment by thmosqueiro** [comment]
Quoting @rougier:
> @thmosqueiro One month would be nice but it can be longer if you need more time.

Since we have a second reviewer, I'll get started. Should be ready soon.

**Comment by rougier** [comment]
@jpgard @thmosqueiro Thansk for accepting to review. Guidelines are at https://rescience.github.io/edit/

The review  is open (obviously) and interactive. Don't hesitate to ask questions if necessary

**Comment by rougier** [comment]
Gentle reminder

**Comment by jpgard** [comment]
thanks for reminder will complete within 1wk

**Comment by rougier** [comment]
@jpgard @thmosqueiro Any tentative date for your review?

**Comment by jpgard** [comment]
Yes, I have this queued up for this week, will have the review complete by Friday. Sorry for delay, thanks for the nudge :).

**Comment by rougier** [comment]
@thmosqueiro Can you do the review by next week ?

**Comment by jpgard** [comment]
@rougier how would you like the review actually submitted? As a comment on this thread?

**Comment by rougier** [comment]
@jpgard yes, exactly.

**Comment by jpgard** [comment]
Below is my review of the article. 

## Replication of the research

The experiment partially, but not fully, replicates the original paper. Some of the original experiments are not replicated (which the authors clearly state); there are differences in some of the experimental setups; and in some cases, results are reported with different hyperparameters than presented in the original paper. 

For example:
* The slot car racing task and real-world robot navigation tasks (Sections 5.3 and 5.7 of original) are not replicated. The authors might wish to state why these are not included in their replication study.
* The distractors in Fig. 5b (compare to original Fig. 7) are implemented differently (rectangles in replication vs. circles in original). The authors should at least provide some motivation as to why this shouldn't make a difference in the results of their replication, or implement with circles instead.
* In the "invariance to perspective" experiment, the authors state that they do not use the authors' original lambda value, because "our implementatino cannot learn any relevant representation", which is the justification for instead presenting results with a lambda value three orders of magnitude smaller. However,later they say that "we tried the original code of the authors with the strong [original] regularization value and it worked as presented in their paper". These seem to contradict each other -- please clarify. Also, it would be useful for the authors to show their results in Figure 4 with the lambda value from the original experiment, not their own manually-selected lambda.
* The authors state in some places that they used "the same hyperparamters" as the original experiment. In the spirit of making this paper self-contained, the authors should clearly state what hyperparameters were used (and which, if any, hyperparameters they selected manually, for examlple if not described in the original work).

I think some rewriting is in order to clearly define the experimental conditions of the current replication, as well as to describe correspondence with the original experiment.

## Reproducibility of the replication

I was not intending to attempt to reproduce the results on my computer, as this seems to be a very computationally-expensive experiment (the standard practice would be to run this on a high-powered research machine). If this is not the case, please advise, and I will attempt to do so. However, I also note that the code does not appear to be in the repository -- the linked code only contains code for building the article, not for generating the experimental results. So, much more is needed in this repository (e.g. the code to conduct the simulations, list of dependencies, commands to execute/reproduce the authors' results including figures).


## Clarity of code and instructions for running

See above -- I did not find any code to reproduce the experiment at the provided code link, only code to reproduce the PDF. 

## Clarity and completeness of the accompanying article

I think the article is quite short, and could use some more analysis to make it self-contained. The authors seem to assume a great deal of knowledge of the original, but an extended introduction which summarizes the original work seems clearly in order here.  In particular, I would recommend summarizing the five robotic priors the original authors proposed, why these are plausible and useful, and how the authors used the proposed priors to formulate the representation learning problem as an optimization problem. As is, these contributions are hardly described in the introduction, which makes it unclear why a replication would be necessary.

Also, since this is a reinforcement learning paper, perhaps you could point to the following articles as further evidence of the importance of replication/reproducibility in reinforcement learning studies:
* Henderson, Peter, et al. "Deep reinforcement learning that matters." Thirty-Second AAAI Conference on Artificial Intelligence. 2018.
* Islam, Riashat, et al. "Reproducibility of benchmarked deep reinforcement learning tasks for continuous control." arXiv preprint arXiv:1708.04133 (2017).

Most of the figures presented match their intended figures in the original quite closely. However, I think more could be done to clearly indicate the correspondence between the replication and the original. For example, in the caption to Figure 2, note that it corresponds to Figure 10a of the original. Similar for the sections: "Invariance to perspective" section corresponds to Section 5.2 of the original.

Some minor typographical notes:
 * Instead of referring to "the article", just cite the original paper. E.g. "We observe that the losses...are less smooth than those in [2]."
 * Capitalize "Figure" when referring to figures in paper.
 * Avoid the use of contractions (e.g. "didn't" --> "did not").

 ## Overall

 I would recommend minor revisions, which would include some rewriting of the article, as well as the major addition of the code (unless this is already available and I missed it somewhere).

**Comment by rougier** [comment]
@jpgard Thanks. @Lcressot can you adress the comment in the paper and most importantly, can you indicate where is your code?

**Comment by thmosqueiro** [comment]
Update on my status: Finalizing my review (writeup).

**Comment by Lcressot** [comment]
Hi,
Thank you very much for the review. I am currently not able to work and update the paper because of a break from an health issue.

Could this wait a moment ?

Cordially,
Loic Cressot

**Comment by rougier** [comment]
Sure.

**Comment by Lcressot** [comment]
Okay thanks, I’ll tell you as soon as I can.

**Comment by rougier** [comment]
Any update ?

**Comment by Lcressot** [comment]
Hi,
Sorry, I didn’t forget you, but I am unfortunately still unable to work. I will keep you updated of the situation in the near future.

Best regards,
Loic Cressot

**Comment by rougier** [comment]
Any update ?

**Comment by Lcressot** [comment]
Hi, still not, I am sorry. I don’t forget you and I will give you some news soon.

Best regards,
Loic

**Comment by Lcressot** [comment]
Hi,

I am very sorry but I recently quit my PhD thesis because of a long lasting health issue. I will pass the ReScience project on to my team and let them contact you, hopefully they will be able to end it soon.

I just have an issue : I don’t remember where to find your review about my submission, so that I can transmit it to my team.


Thanks for your help and again sorry for the inconveniences.

Cordially,
Loic Cressot

**Comment by rougier** [comment]
Oh, I'm sorry to hear that. No problem on our side and we let you decide what you want to do. Either close the submission or hand it to your colleagues, just tell me.
The link is: https://github.com/ReScience/ReScience-submission/pull/54.

**Comment by Lcressot** [comment]
I am handing the project to my team, they may take some time to answer but I hope they can complete the work soon. Thanks for everything.

Sincerely yours,
Loic

**Comment by rougier** [comment]
I'm closing the review until further notice.

**Comment by Lcressot** [comment]
Okay, sorry again. Thanks for your review and help.

**Comment by rougier** [comment]
No problem. Feel free to re-open it if you or one of your colleagues want to work on it again.

**Pull request closed without merging**
