### PR TITLE
Added a PR template to ease submission

### PR DESCRIPTION
**Pull request by rougier**
Comments welcome (do we need more information ?)

### CODE REVIEW

**Comment by eddelbuettel** [comment]
LGTM -- but shouldn't we also change README.md to reference it?

**Comment by rougier** [comment]
Oops, yes, you're right !

**Comment by eddelbuettel** [comment]
LGTM. It quotes it in almost full in `README.md`; I was thinking more of a file link. But added clarity never hurt.

Ready to merge; not sure if you want a second on it.

**Comment by rougier** [comment]
Thanks @eddelbuettel. I think one review is enough.

**Pull request merged**
