### PR TITLE
Tennøe Hodne Haug Weltzien Einevoll Halnes

### PR DESCRIPTION
**Pull request by simetenn**
**AUTHOR**

Dear @ReScience/editors,

I request a review for the following replication:

### Original article

**Title:** Fast-Activating Voltage- and Calcium-Dependent Potassium (BK) Conductance Promotes  Bursting in Pituitary Cells: A Dynamic Clamp Study  
**Author(s):** J. Tabak, M. Tomaiuolo, A. Gonzalez-Iglesias,  L. Milescu and R. Bertram
**Journal (or Conference):** Journal of Neuroscience  
**Year:** 2011  
**DOI:** 10.1523/JNEUROSCI.3235-11.2011  
**PDF:** [http://www.jneurosci.org/content/jneuro/31/46/16855.full.pdf](http://www.jneurosci.org/content/jneuro/31/46/16855.full.pdf)  

### Replication

**Author(s)**: Simen Tennøe, Kjetil Hodne, Trude M. Haug, Finn-Arne Weltzien, Gaute T. Einevoll, and Geir Halnes  
**Repository**: [https://github.com/simetenn/ReScience-submission/tree/tennøe-hodne-haug-weltzien-einevoll-halnes](https://github.com/simetenn/ReScience-submission/tree/tennøe-hodne-haug-weltzien-einevoll-halnes)  
**PDF**: [https://github.com/simetenn/ReScience-submission/tree/tennøe-hodne-haug-weltzien-einevoll-halnes/article/tennøe-hodne-haug-weltzien-einevoll-halnes-2018.pdf](https://github.com/simetenn/ReScience-submission/tree/tennøe-hodne-haug-weltzien-einevoll-halnes/article/tennøe-hodne-haug-weltzien-einevoll-halnes-2018.pdf)  
**Keywords**: Neuroscience, Python, Uncertainty quantification, Pituitary cells  
**Language**: Python  
**Domain**: Computational Neuroscience  

### Results

* [ ] Article has been fully replicated  
* [x] Article has been partially replicated  
* [ ] Article has not been replicated  

### Potential reviewers

---

**EDITOR**

* [x] Editor acknowledgment
* [x] Reviewer 1 (@gdetor `23 November 2018`)
* [x] Reviewer 2 (@apdavison `03 December 2018`)
* [x] Review 1 decision accept (`18 February 2019`)
* [x] Review 2 decision accept (`11 March 2019`)
* [x] Editor decision accept (`11 March 2019`)

### CODE REVIEW

**Comment by rougier** [comment]
Thanks for your submission. An editor will be soon assigned!

@benoit-girard Could you handle this submission (I'll help with the publication step if necessary)

**Comment by benoit-girard** [comment]
@rougier  : OK, I can do it.

**Comment by benoit-girard** [comment]
@stephanmg : are you familiar with Neuron? Do you think you could evaluate this work?
@ChristophMetzner : are you available and willing to evaluate this work?

**Comment by ChristophMetzner** [comment]
@benoit-girard I would be available and would really like to review this submission, however, I have an ongoing collaboration with Gaute Einevoll, which, I guess, constitutes a conflict of interest. Therefore, I think I have to decline.

**Comment by benoit-girard** [comment]
@ChristophMetzner I didn't know about that COI. Sorry.
@miladh : are you familiar with Neuron? Do you think you could evaluate this work?

**Comment by miladh** [comment]
Thanks for asking @benoit-girard, but Gaute Einevoll is my supervisor and I'm working closely with @simetenn in several projects, so I think I also have to decline due to COI.

**Comment by benoit-girard** [comment]
@stephanmg @gdetor : would you be interested in reviewing this submission?

**Comment by benoit-girard** [comment]
@apdavison : could you review this submission?

**Comment by apdavison** [comment]
@benoit-girard I'd be happy to.

I have a small potential conflict of interest, as Gaute Einevoll and I both receive funding under the Human Brain Project grant; however we do not collaborate directly (we are in different sub-projects).

Please let me know if this is a problem; otherwise I will go ahead and review the submission.

**Comment by benoit-girard** [comment]
I tend to think it is not a problem in that case, let's ask the bosses if they agree with me. 
@rougier @khinsen : Do you agree?

**Comment by khinsen** [comment]
For me this is not a problem.

**Comment by gdetor** [comment]
@benoit-girard I can review this submission.

**Comment by benoit-girard** [comment]
Thank you @gdetor you are now reviewer number 1.
@rougier I am waiting for your feedback about @apdavison before validating him as reviewer number 2.

**Comment by rougier** [comment]
Fine for me as well.

**Comment by benoit-girard** [comment]
Then @apdavison you are reviewer 2! Thanks!

**Comment by benoit-girard** [comment]
@apdavison @gdetor : just a gentle reminder... Do you think you could provide a first evaluation mid-January?

**Comment by apdavison** [comment]
Yes, certainly.

**Comment by gdetor** [comment]
@benoit-girard  Yes

**Comment by benoit-girard** [comment]
Dear @apdavison and @gdetor : a gentle reminder...

**Comment by gdetor** [comment]
The authors reliably reproduced the original results of [Fast-Activating Voltage- and Calcium-Dependent Potassium (BK) Conductance Promotes Bursting in Pituitary Cells: A Dynamic Clamp Study]. The results are pretty similar to the original ones (figures 1 and 2 from the original paper). However, an exact match is not possible due to additive noise. In addition the authors through their analysis found out that the bursting behavior is not only affected by the G_{BK} but additionally by other parameters (namely G_K and G_{SK}). These novel results provide more insight bout the bursting in pituitary cells and complete the original work conducted by Tabak et al.. 

All the algorithms and processes followed by the authors are well-explained in the text. The authors took care of all the necessary modifications of the original model equations in order to fulfill Neuron's requirements.  

Part of the original source code (written in XPP) is cited by the authors as well. Furthermore, authors report that all the discrepancies were resolved successfully. 

Source Code 
------------

The source code is well written, clean and licensed. The python scripts and the neuron model files are sufficiently documented. All simulations run smoothly from within the docker file (I couldn't run the clean Python scripts due to a Neuron issue on my machine). 

The platform and package specifications are also provided.  


Text
-----

- page 1-8, paragraph 4: "The average afterhyperpolarization ... in turn most most ..."-> remove the second most.

- page 1-9, in Parameter Exploration section, paragraph 2: "value of G_{BK}, These ..." -> these. 

- The very last sentence in the text (conclusions), contains too many repetitions of the word "model". 


Figures
-------

- Please increase the size of fonts of figures ticks and labels, and make them bold as well. 

- Please make figures colorblind-friendly (authors can use this web page for choosing colorblind-friendly colorschemes: http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3

**Comment by simetenn** [comment]
@gdetor Thank you for the kind review. All your feedback have now been incorporated into the text and figures with the lasts commits.


# Text

* page 1-8, paragraph 4: "The average afterhyperpolarization ... in turn most most ..."-> remove the second most.

The second most have been removed.

* page 1-9, in Parameter Exploration section, paragraph 2: "value of G_{BK}, These ..." -> these.

We have corrected the comma to a punctuation.

* The very last sentence in the text (conclusions), contains too many repetitions of the word "model".

We have corrected the last sentence to: "`The original model now exists as a model using the Python interface for NEURON, which hopefully makes it accessible to a wider audience.`"

# Figures

* Please increase the size of fonts of figures ticks and labels, and make them bold as well.

This is a good point. We have increased the fontsize and fontweight in all the plots.

* Please make figures colorblind-friendly (authors can use this web page for choosing colorblind-friendly colorschemes: http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3

This is another good point. The figures are now hopefully colorblind-friendly. Unfortunately, the colorbrewer website does not have qualitative colorblind-friendly palettes with five colors. Instead, we use the `colorblind` palette from `seaborn` for the plots where this was relevant.

**Comment by apdavison** [comment]
Apologies for the delay in my review. I will try to finish by the end of this week.

**Comment by apdavison** [comment]
**Replication of the research**
The results of the replication are quantitatively close to the original (and go beyond it, giving additional insight through the UQ and sensitivity analysis). The discrepancies are due to: (a) additive noise, (b) differences in integration methods, (c) conversion from total conductances to per-unit-area conductances by choosing a membrane area _A_. While it would be challenging or impossible to reproduce the same random numbers as in the original, I would like to see some examination of the choice of _A_ (which will affect floating point errors) and of the integration method (e.g. do the XPP and NEURON results converge when reducing the time step?)

**Reproducibility of the replication**
Running the simulations in the Docker container produced identical results as in the submission. I did not test a from-scratch installation, but from the Dockerfile I see no reason to expect this wouldn't be straightforward. The dependency versions are given explicitly.

**Clarity of the code and the instructions for running it**
The code is clear, well structured and well documented. The instructions were clear and straightforward.

**Clarity and completeness of the accompanying article**
The article is well written, and explains well the choices made in the replication.

Minor comments:
- in the "Event detection" section "mv" is used in a couple of places instead of "mV"
- in the "Uncertainty quantification..." section, "where assigned" should be "were assigned"
- in the same section, the subscripts (e.g. in G<sub>SK</sub>) are outsized; they are fine elsewhere in the manuscript.
-   in the "Results" section, it should be "results...correspond", not "results...corresponds" in paragraphs 2 and 3.
- in the Conclusion, "effort went smooth" should be "effort went smoothly"

**Comment by simetenn** [comment]
@apdavison Thank you for the kind review. We have now tested for different timesteps and areas, neither of which affects our results. We have added a new section to the paper named "Examining the discrepancies between the replicated and original simulations", which shows this exploration.

Here, there is mainly one results that differ between ours and the original study, namely the result in Figure 2C. We tried but were not able to find a good explanation for this mismatch. However, we note that the authors of the original publication stated that they produced just this robustness result (Figure 2) using custom developed software that used CUDA to run on GPUs. This code was not made available for the readers, and its details are therefore unknown to us. It is possible that, as we suggest in the revised version of the paper, the discrepancies between our and their results stem from differences in definitions made during the analysis (e.g. in spike/burst threshold definitions). It is also possible that there were minor differences between the models used in the XPP and CUDA implementations in the original work, and that this is the explanation to why the discrepancies are largest for just this figure. However, as we had no way to verify or explore this, we did not want to make such speculations in the manuscript.

In addition, we made a slight rewriting of the results and all your feedback on the text have been implemented.

* in the "Event detection" section "mv" is used in a couple of places instead of "mV"

Corrected to "mV".

* in the "Uncertainty quantification..." section, "where assigned" should be "were assigned"

Corrected to "were assigned".

* in the same section, the subscripts (e.g. in GSK) are outsized; they are fine elsewhere in the manuscript.

We used a mix of both `\mathrm{}` and `\textrm{}` in the subscripts. We now only use `\mathrm{}`, so the subscripts should be consistent throughout the manuscript.

* in the "Results" section, it should be "results...correspond", not "results...corresponds" in paragraphs 2 and 3.

We now use correspond instead of corresponds.

* in the Conclusion, "effort went smooth" should be "effort went smoothly"

Corrected to using smoothly.

**Comment by benoit-girard** [comment]
@gdetor @apdavison : are you satisfied with the feedback provided by @simetenn ? Could you provide a second round of reviews (either validating the corrections made or suggesting additional modifications) by the end of February?

**Comment by gdetor** [comment]
@benoit-girard All my comments have been addressed properly. I have no further comments. I endorse the publication of this work.

**Comment by benoit-girard** [comment]
@apdavison Are you satisfied with the authors' reply and modifications?

**Comment by apdavison** [comment]
@benoit-girard I'm afraid I haven't had time to review the changes, but I will do so by the end of this week.

**Comment by apdavison** [comment]
My apologies for the delay. I am very satisfied by the reply and the additional exploration of the remaining discrepancies. Many thanks to the authors for this very nice replication.

**Comment by benoit-girard** [comment]
Given the positive feedback from both reviewers, the paper is accepted, I will now have to take care of the publishing steps (I may not be able to do it this week...).
@rougier : Is the publishing process as tough as it used to be, or have some steps evolved?

**Comment by rougier** [comment]
The new process is far more easier (because authors do all the hard work) but it is not yet online. But I can help you on this one if you want (as I promised at the top of this thread 😄).

**Comment by rougier** [comment]
@benoit-girard Do you need some help with the publishing process

**Comment by benoit-girard** [comment]
Indeed, what should I begin with (compared to the old procedure) ?

**Comment by rougier** [comment]
Well, in this specific case, you have to use the old procedure. Sorry for that.

**Comment by benoit-girard** [comment]
I have begun the process, I am now at the "Rebuild the PDF and check everything is OK" step.
I haven't build a "md" into a pdf in a while, I don't remember how to proceed. Where can I find a description of the process (including the bib processing, which, I vaguely remember, wasn't easy)? I thought it was somewhere in the ReScience repos, but couldn't find it...

**Comment by benoit-girard** [comment]
nevermind, I found it.

**Comment by benoit-girard** [comment]
This time, I am really stuck, at the "Merge the rescience branch into master" step.

I tried : 
git add tennøe-hodne-haug-weltzien-einevoll-halnes-2018.md
git commit -m "Updated meta data fields"

but then, I don't know what to do... help ! @rougier

**Comment by rougier** [comment]
$ git checkout master
$ git merge rescience

If the branch is named rescience. Else you can try `git branch` to check what are the branch in your local repository.

By the way, @simetenn just told me (by email) that there is a small typo in the manuscript:

"The value of the parameter "c" (for NEURON) in Table 1 is written 1.6, but the correct value is 3.18. This mistake is only present in the manuscript". 

Can you correct it while editing it ?

**Comment by rougier** [comment]
@benoit-girard I unlocked the conversation such that authors can comment (about the correction)

**Comment by simetenn** [comment]
@benoit-girard: Just tell me if you want me to submit a commit to this PR with the correction.

**Comment by benoit-girard** [comment]
I did that:

> $ git checkout master
> $ git merge rescience

then I modified the md so as to correct the error:

> By the way, @simetenn just told me (by email) that there is a small typo in the manuscript:
> 
> "The value of the parameter "c" (for NEURON) in Table 1 is written 1.6, but the correct value is 3.18. This mistake is only present in the manuscript".
> 
> Can you correct it while editing it ?

but I get this when I try to push:

 ! [remote rejected] master -> master (permission denied)

This git thing is making me feel helpless once again...

**Comment by benoit-girard** [comment]
@rougier do I need more access rights to ReScience-Archive, or did I something wrong (again)?

**Comment by rougier** [comment]
You're right, I just changed your rights (you should have them all on the archives). Sorry for that.

**Comment by benoit-girard** [comment]
This submission has been accepted for publication. 

[DOI](https://doi.org/10.5281/zenodo.2611252)

**Pull request closed without merging**
