### PR TITLE
Review Request : J. Stachelek

### PR DESCRIPTION
**Pull request by jsta**
**AUTHOR**

  Dear @ReScience/editors,

  I request a review for the replication of the following paper:
- **Least-cost modelling on irregular landscape graphs**, T.R. Etherington. Landscape
  ecology, 27.7, 2012.

I believe the original results have been faithfully replicated
  as explained in the accompanying [article](https://github.com/jsta/ReScience-submission/raw/STACHELEK/article/article.pdf).

The repository lives at [https://github.com/jsta/ReScience-submission/tree/STACHELEK](https://github.com/jsta/ReScience-submission/tree/STACHELEK)

```
git clone https://github.com/jsta/ReScience-submission.git
cd ReScience-submission
git checkout STACHELEK
Rscript -e 'devtools::install_github("jsta/irlgraph", dependencies = TRUE)'
make all
```

---

**EDITOR**
- [x] Editor acknowledgment
- [x] Review 1 started (@dmcglinn) `Nov 17, 2015`
- [x] Review 2 started (@tpoisot) `Nov 18, 2015`
- [x] Review 1 decision [accept/reject] `Feb 22, 2016`
- [x] Review 2 decision [accept/reject] `Feb 22, 2016`
- [x] Editor decision [accept/reject] `March 2, 2016`

### CODE REVIEW

**Comment by jsta** [comment]
**AUTHOR**

My quick search for possible reviewers on Github turned up @Martin-Jung

**Comment by rougier** [comment]
**EDITOR-IN-CHIEF**

Thank you very much for the submission (as well as the suggested name of the reviewer).
An editor should soon acknowledge the submission to start the review. Don't hesitate to remind us if it was not the case in the next few days.

**Comment by jsta** [comment]
**AUTHOR**

Another potential reviewer might be @whalend

**Comment by FedericoV** [comment]
**EXTERN**

A colleague of mine, Duccio Rocchini (http://gis.cri.fmach.it/rocchini/) is quite experience in Python programming and geography and said he'd like to review.  @rougier is it ok to invite him as a reviewer for this?

**Comment by rougier** [comment]
**EDITOR-IN-CHIEF**

Great, I will invite both to register to the board. In the meantime, we found an editor that should soon take over this review. @FedericoV Do you have the GitHub name for Duccio ?

**Comment by karthik** [comment]
**EDITOR**

Hi all,
I just wanted to chime in and say that I'll take over as editor of this submission. I'll follow up with reviewer recommendations shortly.

**Comment by karthik** [comment]
**EDITOR**

Just updating the thread that we'll finalize reviewers in a day or two. Sorry for the delay.

**Comment by karthik** [comment]
**EDITOR**

Reviewer 1, Dan McGlinn @dmcglinn has accepted.

**Comment by tpoisot** [comment]
**REVIEWER 2**

In `Makefile`, the _update_code_ target is rsync'ing local files (from `/home/jose/...`).

**Comment by tpoisot** [comment]
**REVIEWER 2**

`code/README.md` still has a placeholder text.

**Comment by jsta** [comment]
**AUTHOR**

Thanks @tpoisot. Both of the issues arise because of my uncertainty with how to integrate my existing R package into the submission repo. I left the call to rsync in `Makefile` for my own benefit (note it is not called by the _all_ target) but this could be removed or replaced by `git clone` or `curl` or something else.

I left the `code/README.md` file in the repo purely because it appears in the [code repo of the first article](https://github.com/ReScience-Archives/ReScience-Entry-Topalidou-Rougier-2015).  They place all of their code files at top level of the `code` folder whereas I follow the `R` package subfolder conventions. I would prefer simply to remove `code/README.md` in favor of `code/irlgraph/README.md` but I defer to the @ReScience/editors.

This also brings up the issue of `devtools::install_github()` versus `R CMD INSTALL`. Should I be treating the code associated with the article as static (`R CMD INSTALL`) or dynamic (`devtools::install_github()`)?

**Comment by tpoisot** [comment]
**REVIEWER 2**

For the last point -- I think you can use install_github to point to a particular commit using its hash, so you would keep the benefit of using this but still treat the code as essentially static.

**Comment by dmcglinn** [comment]
**REVIEWER 1**

When I run `make all` I get the following error:

```
rsync -av code/irlgraph/vignettes/irlgraph_files/figure-latex/ article
sending incremental file list
rsync: change_dir "/home/danmcglinn/Documents/ReScience-submission//code/irlgraph/vignettes/irlgraph_files/figure-latex" failed: No such file or directory (2)

sent 20 bytes  received 12 bytes  64.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
make: *** [move_images] Error 23
```

**Comment by jsta** [comment]
**AUTHOR**

I'm sorry to hear that @dmcglinn. My guess is that Make is finding the pre-built vignette and not remaking it. `make all` requires that the vignette be built with caching in order to generate the figure output. Do you see that `make all` is calling `Rscript -e 'rmarkdown::render("code/irlgraph/vignettes/irlgraph.Rmd")`?

 Hopefully my latest commit will provide a fix.

**Comment by tpoisot** [comment]
**REVIEWER 2**

This may be because `make` will run the first target by default.

jsta (11/19):

**Comment by jsta** [comment]
**AUTHOR**

I'm not sure that is it because he is having trouble moving files from the vignette cache to the article folder (the third `make` target). The error message indicates that there are no files in the vignette cache to move which suggests that `rmarkdown::render` has not been called.

**Comment by dmcglinn** [comment]
**REVIEWER 1**

commit 843785f seems to have helped. Now I recieved two error messages for not having the R packages `viridis` and `rgeos` installed. Additionally I got the following error message for not having a function definition for `impute_na` 

```
  |......................................                           |  59%
label: impute_na (with options) 
List of 6
 $ eval      : logi TRUE
 $ fig.align : chr "right"
 $ fig.height: num 4
 $ fig.width : num 6
 $ dev       : chr "png"
 $ dpi       : num 100

Quitting from lines 124-131 (irlgraph.Rmd) 
Error in eval(expr, envir, enclos) : could not find function "impute_na"
Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval

Execution halted
```

**Comment by jsta** [comment]
**AUTHOR**

Hmm, I'm not sure why you don't have a function definition for `impute_na`. I see that it is exported in 
`code/irlgraph/NAMESPACE` and in the Roxygen header of `code/irlgraph/R/impute_na.R`.

I believe the `viridis` and `rgeos` errors can be solved by running:
 `Rscript -e 'devtools::install_github("jsta/irlgraph", dependencies = TRUE)'`

**Comment by dmcglinn** [comment]
**REVIEWER 1**

I had run `Rscript -e 'devtools::install_github("jsta/irlgraph", dependencies = TRUE)'`. When I ran it a second time I noticed this message

```
Installing irlgraph
Installing 5 packages: evaluate, formatR, highr, knitr, mime
```

Which indicates that `rgeos` and `viridis` are not identified as dependencies. 

It is strange that `impute_na` is not working because as you say if the package `irlgraph` is loaded this function is available.

**Comment by jsta** [comment]
**AUTHOR**

They are listed in the `Suggests` field of `code/irlgraph/DESCRIPTION`. The documentation of `devtools::install_github` indicates that `dependencies = TRUE` will honor the `Suggests` field. Maybe try:

`Rscript -e 'devtools::install_github("jsta/irlgraph", dependencies = TRUE, build_vignettes = TRUE)`

**Comment by dmcglinn** [comment]
**REVIEWER 1**

That didn't seem to help. In fact now no other packages are installed initially. This may be a `devtools` bug. Here is the R output:

```
Downloading GitHub repo jsta/irlgraph@master
Installing irlgraph
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD  \
  build '/tmp/RtmpPTvpLW/devtools67d529177f2e/jsta-irlgraph-d1fd8c6'  \
  --no-resave-data --no-manual 

* checking for file ‘/tmp/RtmpPTvpLW/devtools67d529177f2e/jsta-irlgraph-d1fd8c6/DESCRIPTION’ ... OK
* preparing ‘irlgraph’:
* checking DESCRIPTION meta-information ... OK
* installing the package to process help pages
* saving partial Rd database
* creating vignettes ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘irlgraph_0.6.tar.gz’

'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD  \
  INSTALL '/tmp/RtmpPTvpLW/irlgraph_0.6.tar.gz'  \
  --library='/home/danmcglinn/R/x86_64-pc-linux-gnu-library/3.2'  \
  --install-tests 

* installing *source* package ‘irlgraph’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (irlgraph)
```

**Comment by jsta** [comment]
**AUTHOR**

Ok, I was able to reproduce your `impute_na` error on a fresh digitalocean cloud server. However, after ff1ef59 I ran the following commands to successfully create the article. Note that the call to `install_github` successfully installed `viridis` and `rgeos`.

```
$ sudo apt-get update
$ sudo apt-get -y install r-base
$ sudo apt-get install git
```

###devtools + dependencies

```
$ sudo apt-get install libcurl4-gnutls-dev
$ sudo apt-get install libxml2-dev
$ sudo apt-get install libssl-dev
$ sudo Rscript -e "install.packages('devtools', repos = 'https://cran.rstudio.com)"
```

###irlgraph + dependencies

```
$ sudo apt-get install libgeos-dev
$ sudo Rscript -e "devtools::install_github('jsta/irlgraph', dependencies = TRUE)"
```

###pandoc + dependencies

```
$ sudo Rscript -e "install.packages('rmarkdown', repos = 'https://cran.rstudio.com)"
$ sudo apt-get install texlive texlive-latex-extra texlive-xetex texlive-fonts-extra
$ sudo apt-get install texlive-bibtex-extra biber
$ sudo wget https://github.com/jgm/pandoc/releases/download/1.15.2/pandoc-1.15.2-1-amd64.deb
$ sudo dpkg -i pandoc-1.15.2-1-amd64.deb
$ sudo apt-get install cabal-install
$ cabal update
$ cabal install pandoc-crossref
```

###imagemagick

```
$ sudo apt-get install imagemagick
```

###checkout source and build

```
$ git clone https://github.com/jsta/ReScience-submission.git
$ cd ReScience-submission
$ git checkout STACHELEK
$ make all
```

**Comment by dmcglinn** [comment]
**REVIEWER 1**

That helped. I was successful at reproducing the paper and its figures. Your specific branch needs to be targeted when getting the code from the git repository.

**Comment by karthik** [comment]
**EDITOR**

> That helped. I was successful at reproducing the paper and its figures. Your specific branch needs to be targeted when getting the code from the git repository.

@jsta If you can update this PR based on Dan's suggestion, it will speed this along. best - K

**Comment by jsta** [comment]
**AUTHOR**

Sorry, I must be misunderstanding. I thought Dan was either pointing out that:
- I was missing a `git checkout STACHELEK` line in my 11/20 comment 

or that:
- he mistakenly ran `git clone https://github.com/ReScience/ReScience-submission.git` instead of `git clone https://github.com/jsta/ReScience-submission.git`

Did you have a specific update in mind?

**Comment by karthik** [comment]
**EDITOR**

@dmcglinn Can you clear up @jsta's question above?

**Comment by dmcglinn** [comment]
**REVIEWER 1**

I apologize for the delay replying here. Yes the instructions given by @jsta in his 11/20 comment will not work unless they are also accompanied by `git checkout STACHELEK`. It seems like these user instructions should go in the `README.md` file.

**Comment by rougier** [comment]
**EDITOR-IN-CHIEF**

Dear all (@jsta, @karthik, @dmcglinn, @tpoisot, @khinsen),

It seems this review is a bit stalled. Is there anything we can do to move it forward ?
If possible, it would be good to have it finished by the end of the year.

**Comment by karthik** [comment]
**EDITOR**

@jsta I believe the ball is still in your court to fix this branch before we can proceed further. Please address this when you get a chance so we can move forward with your submission.

best, - K

**Comment by jsta** [comment]
**AUTHOR**

@karthik Ok, I think I have addressed all the reviewers' concerns including local file movement commands in `Makefile` (843785f), placeholder text in `code/README.md` (87c1bc7), and lack of build instructions in `README.md` (9f94502).

**Comment by jsta** [comment]
**AUTHOR**

~~I have been thinking about making the files in the `code` folder into a [git submodule](http://git-scm.com/book/en/v2/Git-Tools-Submodules). I think this would allow me to better integrate my somewhat independent R package while avoiding local file movements (see my Nov. 18th comment). Good idea or no?~~

**Comment by jsta** [comment]
**AUTHOR**

@karthik @tpoisot @dmcglinn I implemented a Docker pdf build in c03fe28

**Comment by karthik** [comment]
**EDITOR**

@dmcglinn @tpoisot Can you two do a pull from the current PR and build? It works fine for me. If you are also able to replicate, we can close this up before the end of January. Thanks very much. 

PS: It finishes in under a minute.

**Comment by tpoisot** [comment]
**REVIEWER 2**

Sorry for taking my sweet little time about testing.

# Issue 1

Here is what I got:

```
▶ ReScience-submission on STACHELEK is clean $ make all
Rscript -e 'rmarkdown::render("code/irlgraph/vignettes/irlgraph.Rmd")'
Error in loadNamespace(name) : 
  aucun package nommé ‘rmarkdown’ n'est trouvé
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Exécution arrêtée
Makefile:6 : la recette pour la cible « code/irlgraph/vignettes/irlgraph.pdf » a échouée
make: *** [code/irlgraph/vignettes/irlgraph.pdf] Erreur 1
```

I solved this by installing `rmarkdown`.

# Issue 2

Here is the relevant line

```
pandoc --standalone --filter /home/tpoisot/.cabal/bin/pandoc-crossref --template=rescience-template.tex --latex-engine=xelatex --biblatex --bibliography=article.bib -M "crossrefYaml=crossref.yaml" --output article.tex article.md
pandoc: Filter /home/tpoisot/.cabal/bin/pandoc-crossref not found
```

On my system, the filter is called `pandoc-citeproc`, and `pandoc-citeproc` is in the path (and is at `/usr/bin/pandoc-citeproc`).

This one can be solved with the right variables passed to the different makefiles.

**Comment by jsta** [comment]
**AUTHOR**

@tpoisot 
Have you seen the build instructions in `README.md`? They include installation of `rmarkdown`.

Are you able to build the article in the master branch (not STACHELEK)? The master branch `article/README.md` says to use `pandoc-crossref` not `pandoc-citeproc`...
I hope this is not related to the version problem discussed at #13

**Comment by jsta** [comment]
**AUTHOR**

@tpoisot @dmcglinn: According to @rougier in #13, you do not need to actually compile the pdf as reviewers. In order to build only the figures substitute the `make all` line in `README.md` with `make panel-resize_images`. The figure images can then be found in the `article` folder.

Also, you would not need the `Haskell/cabal/pandoc-crossref` dependencies.

**Comment by tpoisot** [comment]
**REVIEWER 2**
@karthik Working, no more comments/requests.
:shipit:

**Comment by rougier** [comment]
**EDITOR-IN-CHIEF**

@karthik @tpoisot @dmcglinn Yes, the review is really about whether the original has been replicatedd or not and whether the new code can be ran easily. The actual buidling of the PDF is not necessary (it will be built once for the journal).  The point of the review is really to check if the article explains why the author think results have been replicated and if the code is "ok" (comments, LICENSE, requirements) such that anybody reading the article can re-use th code.

@jsta Maybe you can remove the top Makefile (and change the README accordingly) to avoi the confusion.

Sorry if the instructions (http://rescience.github.io/edit/) are not clear enough. PR welcome !

**Comment by dmcglinn** [comment]
**REVIEWER 1**

@karthik this is working for me too. I also apologize for the long delays. No more comments.

**Comment by karthik** [comment]
**EDITOR**

Thank you @tpoisot and @dmcglinn 
I'll look this over shortly and update the thread.

**Comment by karthik** [comment]
**EDITOR**

@jsta Apologies for all the delays. But I have also reviewed the submission and the original landscape ecology paper by Etherington and am happy that the original code and figures have been reproduced. I'm happy to accept the submission.

**Comment by jsta** [comment]
**AUTHOR**

Thanks @karthik , please let me know if I can do anything else to prep the PR for import.

**Comment by rougier** [comment]
**EDITOR-IN-CHIEF**

@jsta Until actual import (soon), please do not commit to the repo.
@karthik I can take care of the final publication if you want.

**Comment by rougier** [comment]
**EDITOR-IN-CHIEF**

@karthik I will take care of the publication.
@jsta You need to have all the output images either in your code repository (or in the article repository) such that I can build the PDF without running the code. Does that make sense ?

**Comment by jsta** [comment]
@rougier I have added many images to the repo. You should be able to build
the PDF now.

**Comment by rougier** [comment]
@jsta Thanks.

**Comment by rougier** [comment]
@jsta Could you also give 2/3 keywords ? (We need to add a `keyword` fields in the template)

**Comment by rougier** [comment]
This submission has been accepted for publication, and has been published and will soon appear at https://github.com/ReScience/ReScience/wiki/Current-Issue

[DOI](http://dx.doi.org/10.5281/zenodo.47146)

**Comment by karthik** [comment]
Thanks @rougier!

**Pull request closed without merging**
